//! Vendored, parsed snapshot of pi's generated LLM model catalog.
//!
//! pi (the TypeScript project this repo mirrors) generates its model catalog at
//! build time from `https://models.dev/api.json` plus supplemental provider
//! endpoints; the result is never committed upstream. This crate captures a
//! point-in-time snapshot of that generated catalog under `data/`, embeds the
//! aggregate via [`include_str!`], and exposes it as strongly-typed Rust
//! structs that mirror pi's canonical `Model<TApi>` shape.
//!
//! # Intended pidgin-ai integration
//!
//! pidgin-ai's provider registry consumes [`catalog()`] to enumerate providers
//! and models and to read each model's pricing and capabilities (context
//! window, modalities, reasoning support, thinking-level map) without issuing
//! any network calls of its own. This crate owns only the data and its parsing,
//! while pidgin-ai owns the HTTP clients and per-API request/response handling,
//! so the two can evolve independently against a stable, embedded data surface.
//!
//! # Refreshing
//!
//! The snapshot is regenerated by `scripts/refresh-model-catalog.sh`, which
//! re-runs pi's generator at the current submodule pin and rewrites `data/`.
//! Refreshing is a manual, non-gating step tied to upstream pin bumps.

mod catalog;
mod types;

pub use catalog::{catalog, manifest, Catalog, Manifest};
pub use types::{Modality, Model, ModelCost, ModelCostRates, ModelCostTier};
