//! Build step: derive `src/generated.wired.rs` from the fluessig-generated
//! `src/generated.rs` without editing that do-not-edit file.
//!
//! # Why this exists
//!
//! `ext-php-rs` 0.13.1 registers PHP classes through a single crate-wide
//! `#[php_module]` (which lives in `src/generated.rs`). That macro expands
//! `impl RegisteredClass for <Ident>` for *every* `#[php_class]` in the crate at
//! the module's own call site, referencing each class by its **bare** identifier.
//! So the hand-authored `Pidgin\Session` class (in `src/session.rs`) is only
//! resolvable if the name `Session` is in scope where `#[php_module]` expands.
//!
//! We must not edit `src/generated.rs` (it is regenerated by `regen.sh`), and we
//! cannot inject a name into a plain `mod generated;` file module from outside,
//! nor `include!` the file (its leading inner attributes/doc-comments are illegal
//! in `include!` position). We also cannot use `include!` into an inline module,
//! because that reorders macro expansion and trips ext-php-rs's "module must be
//! called last" guard.
//!
//! The one mechanism that keeps correct macro-expansion ordering *and* injects a
//! name into the generated module's scope is a **file module loaded via
//! `#[path]`**. So this build step copies `generated.rs` verbatim and inserts a
//! single `use crate::session::Session;` after its import header, writing the
//! result to `generated.wired.rs`, which `lib.rs` mounts with
//! `#[path = "generated.wired.rs"] mod generated;`. The original `generated.rs`
//! is never touched, so `regen.sh` stays authoritative.

use std::fs;
use std::path::Path;

fn main() {
    let src_path = "src/generated.rs";
    let out_path = "src/generated.wired.rs";

    println!("cargo:rerun-if-changed={src_path}");
    println!("cargo:rerun-if-changed=build.rs");
    // Also watch the output: if it is deleted or hand-edited, regenerate it even
    // when `generated.rs` itself has not changed. The content-guard below keeps
    // this from looping (an unchanged result is not rewritten, so its mtime is
    // stable and cargo stops re-triggering).
    println!("cargo:rerun-if-changed={out_path}");

    let src = fs::read_to_string(src_path)
        .unwrap_or_else(|e| panic!("build.rs: cannot read {src_path}: {e}"));

    let inject = "use crate::session::Session;";
    let lines: Vec<&str> = src.lines().collect();

    // Walk the contiguous header region (inner doc-comments `//!`, inner
    // attributes `#![...]`, plain `//` comments, blank lines, and `use ...;`
    // imports) and insert the injection right after it — before the first item
    // (an outer `///` doc or a definition). `///` outer docs end the header.
    let mut insert_at = 0usize;
    for (i, line) in lines.iter().enumerate() {
        let t = line.trim_start();
        if t.starts_with("///") {
            break;
        }
        if t.is_empty() || t.starts_with("//") || t.starts_with("#![") || t.starts_with("use ") {
            insert_at = i + 1;
        } else {
            break;
        }
    }

    let mut out_lines = lines.clone();
    out_lines.insert(insert_at, inject);
    let out = format!("{}\n", out_lines.join("\n"));

    // Avoid rewriting (and thus needlessly re-touching mtime) when unchanged.
    let changed = match fs::read_to_string(out_path) {
        Ok(existing) => existing != out,
        Err(_) => true,
    };
    if changed {
        fs::write(Path::new(out_path), out)
            .unwrap_or_else(|e| panic!("build.rs: cannot write {out_path}: {e}"));
    }
}
