#!/usr/bin/env bash
# Regenerate src/generated.rs from schema/ using fluessig-gen.
#
# Pipeline: schema/api.json + schema/catalog.json  --fluessig-gen-->  src/generated.rs
# The generated file is do-not-edit; change the schema and rerun this script.
#
# fluessig is pinned to rev b6cad5fa8bc59a7f9c4984b1464e8c1d84796466
# (zmaril/fluessig#58, the PHP-header fix). Keep this in sync with the
# `fluessig-runtime` rev in Cargo.toml — the generated code and the runtime
# crate must come from the same fluessig revision.
set -euo pipefail

pinned_rev="b6cad5fa8bc59a7f9c4984b1464e8c1d84796466"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Resolve the fluessig checkout: first arg, then $FLUESSIG_DIR, then the
# conventional sibling location next to the atilla repo.
fluessig_dir="${1:-${FLUESSIG_DIR:-$here/../../../fluessig}}"

if [[ ! -d "$fluessig_dir" ]]; then
    echo "ERROR: fluessig checkout not found at '$fluessig_dir'." >&2
    echo "Pass it as an argument or set FLUESSIG_DIR." >&2
    exit 1
fi
fluessig_dir="$(cd "$fluessig_dir" && pwd)"

echo "fluessig checkout: $fluessig_dir"
echo "pinned rev (keep in sync with Cargo.toml fluessig-runtime): $pinned_rev"

echo "building fluessig-gen..."
( cd "$fluessig_dir" && cargo build --release --bin fluessig-gen )

gen_bin="$fluessig_dir/target/release/fluessig-gen"
if [[ ! -x "$gen_bin" ]]; then
    echo "ERROR: fluessig-gen not found at '$gen_bin' after build." >&2
    exit 1
fi

# The positional <out.rs> schema module is required by the CLI but is not part
# of this crate — write it to a throwaway temp file and discard it.
throwaway="$(mktemp -t fluessig-schema-XXXXXX.rs)"
trap 'rm -f "$throwaway"' EXIT

echo "generating src/generated.rs..."
"$gen_bin" \
    "$here/schema/catalog.json" \
    "$throwaway" \
    --api "$here/schema/api.json" \
    --php "$here/src/generated.rs" \
    --banner-note "straitjacket-allow-file:duplication — generated by fluessig; edit the schema instead"

echo
echo "wrote $here/src/generated.rs (do not edit by hand)."
echo "Next: cargo fmt && cargo clippy --all-targets -- -D warnings && ./test.sh"
