// straitjacket-allow-file:duplication — this sibling of generate-manifest.mjs
// necessarily repeats the node:fs/path import block, the here/repoRoot/piRoot
// path-constant setup, and the tiny directory walk() helper; each script stands
// alone as its own entry point and the overlap is unavoidable boilerplate.
//
// Conformance shim codegen.
//
// Reads conformance/manifest.json, which classifies every pi source module as
// "original" (pi's own file, used unchanged — a pass-through, no file written)
// or "native" (backed by the atilla Rust addon — a shim TS file is generated
// that re-exports the binding). No module is native yet, so the generated tree
// is pi itself; that is the point — it proves the machinery end to end.
//
// The script also validates that the manifest exactly covers the current
// vendored pi source tree, reporting drift in either direction, and prints a
// summary { total, native, original, missing }.
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { isSourceModule } from "./generate-manifest.mjs";

const here = fileURLToPath(new URL(".", import.meta.url));
const repoRoot = join(here, "..");
const piRoot = join(repoRoot, "vendor", "pi");
const packagesDir = join(piRoot, "packages");
const genRoot = join(here, "generated");
const shimsRoot = join(here, "shims");

// Suffix marking a preserved pi original next to a native shim. The shim
// re-exports the un-ported surface from this sibling; scripts/conformance.sh
// removes these backups (and restores the overwritten originals) after a run.
const ORIGINAL_SUFFIX = ".__pi_original__.ts";

function walk(dir, acc) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(full);
  }
}

/** Every source module currently on disk, as pi-relative paths. */
function modulesOnDisk() {
  const found = new Set();
  for (const pkg of readdirSync(packagesDir)) {
    const srcDir = join(packagesDir, pkg, "src");
    try {
      if (!statSync(srcDir).isDirectory()) continue;
    } catch {
      continue;
    }
    const files = [];
    walk(srcDir, files);
    for (const full of files) {
      const rel = relative(piRoot, full).split("\\").join("/");
      if (isSourceModule(rel)) found.add(rel);
    }
  }
  return found;
}

/** Resolve the shim body for a native module: a hand-written shim under
 * conformance/shims/ if present, else a generic Rust-addon re-export. */
function shimBody(row) {
  const handWritten = join(shimsRoot, row.src);
  if (existsSync(handWritten)) {
    return { body: readFileSync(handWritten, "utf8"), handWritten: true };
  }
  const body = [
    "// AUTOGENERATED by conformance/codegen.mjs — do not edit.",
    `// Native shim for ${row.src}; backed by the atilla Rust addon.`,
    'export * from "atilla-napi";',
    "",
  ].join("\n");
  return { body, handWritten: false };
}

/**
 * Materialize a native module: record the generated shim, then overlay it onto
 * the vendored pi tree so pi's tests (which import `../src/...` by relative path)
 * resolve to the Rust-backed shim. The original pi file is preserved next to the
 * shim as `<name>.__pi_original__.ts` — a hand-written shim re-exports its
 * un-ported surface from there. scripts/conformance.sh restores the tree after
 * the run.
 */
function writeNativeShim(row) {
  const { body, handWritten } = shimBody(row);

  // 1. Keep an inspectable copy under conformance/generated/ (gitignored).
  const genPath = join(genRoot, row.src);
  mkdirSync(dirname(genPath), { recursive: true });
  writeFileSync(genPath, body);

  // 2. Overlay into the vendored pi tree.
  const targetPath = join(piRoot, row.src);
  if (existsSync(targetPath)) {
    if (handWritten) {
      // Preserve pi's original beside the shim for the shim to re-export from.
      const originalPath = join(
        dirname(targetPath),
        basename(targetPath).replace(/\.ts$/, ORIGINAL_SUFFIX),
      );
      if (!existsSync(originalPath)) {
        copyFileSync(targetPath, originalPath);
      }
    }
    writeFileSync(targetPath, body);
  }

  return genPath;
}

/**
 * Overlay a hand-written repointed CLI test file onto the vendored pi tree.
 * The repoint swaps pi's `spawn(process.execPath, [cliPath, ...])` for
 * `spawn(ATILLA_BIN, [...])` so the file exercises the compiled atilla binary
 * instead of pi's own cli.ts. Same overlay contract as native shims: pi's
 * original test file is preserved beside it as `<name>.__pi_original__.ts`, and
 * scripts/conformance.sh restores the tree after the run. Unlike native shims
 * these targets live under `test/`, not `src/`, so they never touch the module
 * drift check. A repoint whose hand-written copy is missing is a hard error —
 * there is no generic fallback for a CLI test.
 */
function writeCliRepoint(row) {
  const handWritten = join(shimsRoot, row.src);
  if (!existsSync(handWritten)) {
    throw new Error(`cli_repoint ${row.src}: no hand-written copy at ${handWritten}`);
  }
  const body = readFileSync(handWritten, "utf8");

  // Keep an inspectable copy under conformance/generated/ (gitignored).
  const genPath = join(genRoot, row.src);
  mkdirSync(dirname(genPath), { recursive: true });
  writeFileSync(genPath, body);

  // Overlay into the vendored pi tree, preserving pi's original beside it.
  const targetPath = join(piRoot, row.src);
  if (existsSync(targetPath)) {
    const originalPath = join(
      dirname(targetPath),
      basename(targetPath).replace(/\.ts$/, ORIGINAL_SUFFIX),
    );
    if (!existsSync(originalPath)) {
      copyFileSync(targetPath, originalPath);
    }
    writeFileSync(targetPath, body);
  }
  return genPath;
}

function main() {
  const manifestPath = join(here, "manifest.json");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const rows = manifest.modules ?? [];
  const cliRepoint = manifest.cli_repoint ?? [];

  const inManifest = new Set(rows.map((r) => r.src));
  const onDisk = modulesOnDisk();

  // Drift: on disk but absent from the manifest.
  const missing = [...onDisk].filter((p) => !inManifest.has(p)).sort();
  // Drift: in the manifest but gone from disk.
  const stale = [...inManifest].filter((p) => !onDisk.has(p)).sort();

  let native = 0;
  let original = 0;
  for (const row of rows) {
    if (row.status === "native") {
      writeNativeShim(row);
      native += 1;
    } else {
      original += 1; // pass-through: pi's own file, used unchanged.
    }
  }

  // Overlay the repointed CLI test files (black-box conformance against the
  // compiled atilla binary). Tracked separately from the module counts above.
  for (const row of cliRepoint) writeCliRepoint(row);

  const summary = {
    total: rows.length,
    native,
    original,
    missing: missing.length,
    cli_repoint: cliRepoint.length,
  };
  console.log(JSON.stringify(summary, null, 2));

  if (missing.length) {
    console.error(`\nmissing from manifest (${missing.length}):`);
    for (const p of missing) console.error(`  + ${p}`);
  }
  if (stale.length) {
    console.error(`\nstale in manifest, gone from disk (${stale.length}):`);
    for (const p of stale) console.error(`  - ${p}`);
  }
  if (missing.length || stale.length) {
    process.exitCode = 1;
  }
}

main();
