// Conformance shim codegen.
//
// Reads conformance/manifest.json, which classifies every pi source module as
// "original" (pi's own file, used unchanged — a pass-through, no file written)
// or "native" (backed by the atilla Rust addon — a shim TS file is generated
// that re-exports the binding). No module is native yet, so the generated tree
// is pi itself; that is the point — it proves the machinery end to end.
//
// The script also validates that the manifest exactly covers the current
// vendored pi source tree, reporting drift in either direction, and prints a
// summary { total, native, original, missing }.
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { isSourceModule } from "./generate-manifest.mjs";

const here = fileURLToPath(new URL(".", import.meta.url));
const repoRoot = join(here, "..");
const piRoot = join(repoRoot, "vendor", "pi");
const packagesDir = join(piRoot, "packages");
const genRoot = join(here, "generated");

function walk(dir, acc) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(full);
  }
}

/** Every source module currently on disk, as pi-relative paths. */
function modulesOnDisk() {
  const found = new Set();
  for (const pkg of readdirSync(packagesDir)) {
    const srcDir = join(packagesDir, pkg, "src");
    try {
      if (!statSync(srcDir).isDirectory()) continue;
    } catch {
      continue;
    }
    const files = [];
    walk(srcDir, files);
    for (const full of files) {
      const rel = relative(piRoot, full).split("\\").join("/");
      if (isSourceModule(rel)) found.add(rel);
    }
  }
  return found;
}

/** Write a shim TS file that re-exports the Rust-backed binding for a module. */
function writeNativeShim(row) {
  const outPath = join(genRoot, row.src.replace(/\.ts$/, ".ts"));
  mkdirSync(dirname(outPath), { recursive: true });
  const body = [
    "// AUTOGENERATED by conformance/codegen.mjs — do not edit.",
    `// Native shim for ${row.src}; backed by the atilla Rust addon.`,
    'export * from "atilla-napi";',
    "",
  ].join("\n");
  writeFileSync(outPath, body);
  return outPath;
}

function main() {
  const manifestPath = join(here, "manifest.json");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const rows = manifest.modules ?? [];

  const inManifest = new Set(rows.map((r) => r.src));
  const onDisk = modulesOnDisk();

  // Drift: on disk but absent from the manifest.
  const missing = [...onDisk].filter((p) => !inManifest.has(p)).sort();
  // Drift: in the manifest but gone from disk.
  const stale = [...inManifest].filter((p) => !onDisk.has(p)).sort();

  let native = 0;
  let original = 0;
  for (const row of rows) {
    if (row.status === "native") {
      writeNativeShim(row);
      native += 1;
    } else {
      original += 1; // pass-through: pi's own file, used unchanged.
    }
  }

  const summary = { total: rows.length, native, original, missing: missing.length };
  console.log(JSON.stringify(summary, null, 2));

  if (missing.length) {
    console.error(`\nmissing from manifest (${missing.length}):`);
    for (const p of missing) console.error(`  + ${p}`);
  }
  if (stale.length) {
    console.error(`\nstale in manifest, gone from disk (${stale.length}):`);
    for (const p of stale) console.error(`  - ${p}`);
  }
  if (missing.length || stale.length) {
    process.exitCode = 1;
  }
}

main();
