// straitjacket-allow-file:duplication — this sibling of generate-manifest.mjs
// necessarily repeats the node:fs/path import block, the here/repoRoot/piRoot
// path-constant setup, and the tiny directory walk() helper; each script stands
// alone as its own entry point and the overlap is unavoidable boilerplate.
//
// Conformance shim codegen.
//
// Reads conformance/manifest.json, which classifies every pi source module as
// "original" (pi's own file, used unchanged — a pass-through, no file written)
// or "native" (backed by the pidgin Rust addon — a shim TS file is generated
// that re-exports the binding). No module is native yet, so the generated tree
// is pi itself; that is the point — it proves the machinery end to end.
//
// The script also validates that the manifest exactly covers the current
// vendored pi source tree, reporting drift in either direction, and prints a
// summary { total, native, original, missing }.
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  rmdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { isSourceModule } from "./generate-manifest.mjs";

const here = fileURLToPath(new URL(".", import.meta.url));
const repoRoot = join(here, "..");
const piRoot = join(repoRoot, "vendor", "pi");
const packagesDir = join(piRoot, "packages");
const genRoot = join(here, "generated");
const shimsRoot = join(here, "shims");

// Suffix marking a preserved pi original next to a native shim. The shim
// re-exports the un-ported surface from this sibling; scripts/conformance.sh
// removes these backups (and restores the overwritten originals) after a run.
const ORIGINAL_SUFFIX = ".__pi_original__.ts";

function walk(dir, acc) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, acc);
    else acc.push(full);
  }
}

/** Every source module currently on disk, as pi-relative paths. */
function modulesOnDisk() {
  const found = new Set();
  for (const pkg of readdirSync(packagesDir)) {
    const srcDir = join(packagesDir, pkg, "src");
    try {
      if (!statSync(srcDir).isDirectory()) continue;
    } catch {
      continue;
    }
    const files = [];
    walk(srcDir, files);
    for (const full of files) {
      const rel = relative(piRoot, full).split("\\").join("/");
      if (isSourceModule(rel)) found.add(rel);
    }
  }
  return found;
}

/** Resolve the shim body for a native module: a hand-written shim under
 * conformance/shims/ if present, else a generic Rust-addon re-export. */
function shimBody(row) {
  const handWritten = join(shimsRoot, row.src);
  if (existsSync(handWritten)) {
    return { body: readFileSync(handWritten, "utf8"), handWritten: true };
  }
  const body = [
    "// AUTOGENERATED by conformance/codegen.mjs — do not edit.",
    `// Native shim for ${row.src}; backed by the pidgin Rust addon.`,
    'export * from "pidgin-napi";',
    "",
  ].join("\n");
  return { body, handWritten: false };
}

/**
 * Materialize a native module: record the generated shim, then overlay it onto
 * the vendored pi tree so pi's tests (which import `../src/...` by relative path)
 * resolve to the Rust-backed shim. The original pi file is preserved next to the
 * shim as `<name>.__pi_original__.ts` — a hand-written shim re-exports its
 * un-ported surface from there. scripts/conformance.sh restores the tree after
 * the run.
 */
function writeNativeShim(row) {
  const { body, handWritten } = shimBody(row);

  // 1. Keep an inspectable copy under conformance/generated/ (gitignored).
  const genPath = join(genRoot, row.src);
  mkdirSync(dirname(genPath), { recursive: true });
  writeFileSync(genPath, body);

  // 2. Overlay into the vendored pi tree.
  const targetPath = join(piRoot, row.src);
  if (existsSync(targetPath)) {
    if (handWritten) {
      // Preserve pi's original beside the shim for the shim to re-export from.
      const originalPath = join(
        dirname(targetPath),
        basename(targetPath).replace(/\.ts$/, ORIGINAL_SUFFIX),
      );
      if (!existsSync(originalPath)) {
        copyFileSync(targetPath, originalPath);
      }
    }
    writeFileSync(targetPath, body);
  }

  return genPath;
}

/**
 * Overlay a hand-written repointed CLI test file onto the vendored pi tree.
 * The repoint swaps pi's `spawn(process.execPath, [cliPath, ...])` for
 * `spawn(PIDGIN_BIN, [...])` so the file exercises the compiled pidgin binary
 * instead of pi's own cli.ts. Same overlay contract as native shims: pi's
 * original test file is preserved beside it as `<name>.__pi_original__.ts`, and
 * scripts/conformance.sh restores the tree after the run. Unlike native shims
 * these targets live under `test/`, not `src/`, so they never touch the module
 * drift check. A repoint whose hand-written copy is missing is a hard error —
 * there is no generic fallback for a CLI test.
 */
function writeCliRepoint(row) {
  const handWritten = join(shimsRoot, row.src);
  if (!existsSync(handWritten)) {
    throw new Error(`cli_repoint ${row.src}: no hand-written copy at ${handWritten}`);
  }
  const body = readFileSync(handWritten, "utf8");

  // Keep an inspectable copy under conformance/generated/ (gitignored).
  const genPath = join(genRoot, row.src);
  mkdirSync(dirname(genPath), { recursive: true });
  writeFileSync(genPath, body);

  // Overlay into the vendored pi tree, preserving pi's original beside it.
  const targetPath = join(piRoot, row.src);
  if (existsSync(targetPath)) {
    const originalPath = join(
      dirname(targetPath),
      basename(targetPath).replace(/\.ts$/, ORIGINAL_SUFFIX),
    );
    if (!existsSync(originalPath)) {
      copyFileSync(targetPath, originalPath);
    }
    writeFileSync(targetPath, body);
  }
  return genPath;
}

/**
 * Overlay net-new, shim-local helper files onto the vendored pi tree.
 *
 * A shim under conformance/shims/ normally corresponds 1:1 to a manifest row
 * (native module) or a cli_repoint entry, and is overlaid by writeNativeShim /
 * writeCliRepoint above. But a flip may also ship SHARED HELPER files under the
 * shim tree — e.g. packages/agent/src/_bridge/dispatcher.ts imported by an
 * overlaid shim — that have NO manifest row and NO pi original to preserve.
 * Those helpers must still land in vendor/pi so the importing shim resolves at
 * conformance time.
 *
 * Walks every file under conformance/shims/ (nested dirs included) and, for each
 * that is NOT already accounted for by a manifest row / cli_repoint entry:
 *   - target absent in vendor/pi  → COPY it in (net-new helper; parents created).
 *   - target already present      → ABORT. A row-less shim that would overwrite
 *     a real pi source is silent drift (a shadow with no manifest flip) and must
 *     be caught, not overlaid.
 *
 * No `.__pi_original__.ts` backup is written: there is no original to preserve.
 * Restoration is stateless — restoreHelpers() re-walks the shim tree and deletes
 * the mirrored net-new targets — so the copied set need not be persisted.
 *
 * @param {Set<string>} handledSrcs pi-relative src paths already overlaid.
 * @returns {string[]} absolute target paths copied in.
 */
function overlayHelpers(handledSrcs) {
  if (!existsSync(shimsRoot)) return [];
  const files = [];
  walk(shimsRoot, files);
  const copied = [];
  for (const full of files) {
    const rel = relative(shimsRoot, full).split("\\").join("/");
    if (handledSrcs.has(rel)) continue; // manifest-row / cli_repoint shim, already overlaid.
    const target = join(piRoot, rel);
    if (existsSync(target)) {
      throw new Error(
        `shim ${rel} has no manifest row but its vendor/pi target already exists ` +
          `(${relative(repoRoot, target)}). A row-less shim must not silently shadow a ` +
          `real pi source — add a manifest row to flip it, or remove the shim.`,
      );
    }
    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(full, target);
    copied.push(target);
  }
  return copied;
}

/** The set of pi-relative src paths accounted for by the manifest. */
function handledSrcSet(manifest) {
  const rows = manifest.modules ?? [];
  const cliRepoint = manifest.cli_repoint ?? [];
  return new Set([...rows.map((r) => r.src), ...cliRepoint.map((r) => r.src)]);
}

/** Prune empty ancestor dirs of `dir`, stopping at (and never removing)
 * vendor/pi/packages. */
function pruneEmptyDirs(dir) {
  const stop = join(piRoot, "packages");
  let cur = dir;
  while (cur !== stop && cur.startsWith(stop + "/")) {
    try {
      if (readdirSync(cur).length !== 0) break;
      rmdirSync(cur);
    } catch {
      break;
    }
    cur = dirname(cur);
  }
}

/**
 * Restore the pi tree of net-new helpers overlaid by overlayHelpers().
 *
 * Because copied helpers are UNTRACKED in vendor/pi, `git checkout -- packages`
 * (run by scripts/conformance.sh after this) will not remove them. This re-walks
 * the shim tree, recomputes the same net-new helper set, and deletes each
 * mirrored target plus its now-empty parent dirs so `git -C vendor/pi status` is
 * byte-clean. Stateless and idempotent: safe to run before a run, after it, or
 * after an interrupted run. A target that has a `.__pi_original__.ts` sibling was
 * a real overlay (not a net-new helper) and is left to the normal restore path.
 */
function restoreHelpers() {
  if (!existsSync(shimsRoot)) return;
  const manifest = JSON.parse(readFileSync(join(here, "manifest.json"), "utf8"));
  const handled = handledSrcSet(manifest);
  const files = [];
  walk(shimsRoot, files);
  for (const full of files) {
    const rel = relative(shimsRoot, full).split("\\").join("/");
    if (handled.has(rel)) continue; // manifest-row shim: normal restore handles it.
    const target = join(piRoot, rel);
    const originalSibling = join(
      dirname(target),
      basename(target).replace(/\.ts$/, ORIGINAL_SUFFIX),
    );
    if (existsSync(originalSibling)) continue; // a preserved overlay, not a net-new helper.
    if (existsSync(target)) {
      rmSync(target);
      pruneEmptyDirs(dirname(target));
    }
  }
}

function main() {
  const manifestPath = join(here, "manifest.json");
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const rows = manifest.modules ?? [];
  const cliRepoint = manifest.cli_repoint ?? [];

  const inManifest = new Set(rows.map((r) => r.src));
  const onDisk = modulesOnDisk();

  // Drift: on disk but absent from the manifest.
  const missing = [...onDisk].filter((p) => !inManifest.has(p)).sort();
  // Drift: in the manifest but gone from disk.
  const stale = [...inManifest].filter((p) => !onDisk.has(p)).sort();

  let native = 0;
  let original = 0;
  for (const row of rows) {
    if (row.status === "native") {
      writeNativeShim(row);
      native += 1;
    } else {
      original += 1; // pass-through: pi's own file, used unchanged.
    }
  }

  // Overlay the repointed CLI test files (black-box conformance against the
  // compiled pidgin binary). Tracked separately from the module counts above.
  for (const row of cliRepoint) writeCliRepoint(row);

  // Overlay net-new, shim-local helper files (no manifest row, no pi original),
  // e.g. packages/agent/src/_bridge/*.ts imported by an overlaid shim. Runs
  // AFTER the drift computation above so it never perturbs the missing count.
  overlayHelpers(handledSrcSet(manifest));

  const summary = {
    total: rows.length,
    native,
    original,
    missing: missing.length,
    cli_repoint: cliRepoint.length,
  };
  console.log(JSON.stringify(summary, null, 2));

  if (missing.length) {
    console.error(`\nmissing from manifest (${missing.length}):`);
    for (const p of missing) console.error(`  + ${p}`);
  }
  if (stale.length) {
    console.error(`\nstale in manifest, gone from disk (${stale.length}):`);
    for (const p of stale) console.error(`  - ${p}`);
  }
  if (missing.length || stale.length) {
    process.exitCode = 1;
  }
}

if (process.argv.includes("--restore")) {
  restoreHelpers();
} else {
  main();
}
