// Builds the markdown body for the conformance sticky PR comment.
//
// Reads two conformance.json documents and compares them like-for-like over the
// packages the CI smoke run actually exercised (agent, ai, tui):
//   argv[2] — fresh results generated by this CI run (default: conformance.json)
//   argv[3] — committed baseline snapshot taken before the run
//
// Prints markdown to stdout. Only the packages present in the fresh results are
// reported, each with its current totals and the passing/failing delta against
// the same package in the baseline. The full five-package baseline stays in the
// committed conformance.json; this comment covers the smoke subset only.
import { readFileSync } from "node:fs";

const currentPath = process.argv[2] || "conformance.json";
const baselinePath = process.argv[3];

function readMaybe(path) {
  if (!path) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

function signed(delta) {
  if (delta > 0) return `+${delta}`;
  if (delta < 0) return `${delta}`;
  return "±0"; // ±0
}

function pkgStats(doc, pkg) {
  const p = doc?.by_package?.[pkg];
  if (!p) return null;
  return {
    rustBackedPassing: p.rust_backed_passing ?? 0,
    rustBackedPercent: p.rust_backed_percent ?? 0,
    total: p.total ?? 0,
    passing: p.passing ?? 0,
    failing: p.failing ?? 0,
    skipped: p.skipped ?? 0,
    native: p.native ?? 0,
  };
}

/**
 * The attribution note, printed verbatim in the sticky comment so the
 * rust-backed number can't be misread. The definition and the per-file
 * counted / mixed-excluded / no-test list are pinned here.
 */
function attributionSection(lines) {
  lines.push("### Attribution");
  lines.push("");
  lines.push(
    "A pi test **file** is *rust-backed* iff the module it primarily exercises — its " +
      "module-under-test — is `status=native` in `conformance/manifest.json`. A package's " +
      "rust-backed count is the passing cases in its rust-backed files. Transitive or " +
      "infrastructure use does not count (e.g. ~30 ai files construct the native faux " +
      "provider but test other things — only `faux-provider.test.ts`, whose subject is " +
      "faux, counts). A file that substantially tests both a native and an original module " +
      "is excluded rather than counted, so the number under-reports rather than over-claims.",
  );
  lines.push("");
  lines.push("Per-file decisions (from each native manifest row's `tests` list):");
  lines.push("");
  lines.push("| Native module | Test file | Decision |");
  lines.push("| --- | --- | --- |");
  const rows = [
    ["ai/api/anthropic-messages.ts", "test/anthropic-sse-parsing.test.ts", "counted"],
    ["ai/providers/faux.ts", "test/faux-provider.test.ts", "counted"],
    ["coding-agent/utils/ansi.ts", "test/ansi-utils.test.ts", "counted"],
    ["coding-agent/utils/changelog.ts", "test/changelog.test.ts", "counted"],
    ["coding-agent/utils/git.ts", "test/git-ssh-url.test.ts", "counted"],
    ["coding-agent/core/tools/path-utils.ts", "test/path-utils.test.ts", "counted"],
    ["tui/keys.ts", "test/keys.test.ts", "counted"],
    ["tui/utils.ts", "test/truncate-to-width.test.ts, test/regression-regional-indicator-width.test.ts", "counted"],
    [
      "coding-agent/utils/mime.ts",
      "test/image-process.test.ts",
      "mixed — excluded (2 of 3 cases test processImage/original)",
    ],
    [
      "coding-agent/utils/version-check.ts",
      "test/version-check.test.ts",
      "mixed — excluded (fetch cases mock the original; not separable per-file)",
    ],
    [
      "coding-agent/core/export-html/ansi-to-html.ts",
      "test/export-html-whitespace.test.ts",
      "mixed — excluded (asset-grep + tool-renderer/original dominate)",
    ],
    [
      "coding-agent/core/tools/truncate.ts",
      "—",
      "no dedicated test (exercised via tools.test.ts, subject is the read/edit factory/original)",
    ],
    [
      "coding-agent/core/tools/edit-diff.ts",
      "—",
      "no dedicated test (edit-tool tests' subject is the edit tool/original)",
    ],
  ];
  for (const [mod, file, decision] of rows) {
    lines.push(`| \`${mod}\` | ${file} | ${decision} |`);
  }
}

/**
 * Append the black-box CLI conformance section. This is a distinct signal from
 * the module smoke table above: it reports the four repointed coding-agent CLI
 * test files run against the compiled pidgin binary, and is never folded into
 * the per-package Native count. Renders nothing when the run produced no
 * cli_conformance block (older results or a run that skipped it).
 */
function cliSection(lines, current, baseline) {
  const cli = current?.cli_conformance;
  if (!cli) return;
  lines.push("");
  lines.push("### CLI conformance (black-box, against the pidgin binary)");
  lines.push("");
  // Show the repo-relative binary path (target/release/pidgin) when possible.
  const binTail = cli.bin && cli.bin.includes("/target/")
    ? "target/" + cli.bin.split("/target/").pop()
    : cli.bin;
  const bin = binTail ? `\`${binTail}\`` : "the pidgin binary";
  if (cli.status !== "ok") {
    lines.push(`- CLI conformance: env-blocked — ${cli.note || "binary unavailable"}.`);
    lines.push("");
    lines.push(
      "Tracked separately from the module smoke above; it is not part of any " +
        "per-package Native count.",
    );
    return;
  }
  const baseCli = baseline?.cli_conformance;
  const passDelta = baseCli ? signed(cli.passing - baseCli.passing) : "n/a";
  const failDelta = baseCli ? signed(cli.failing - baseCli.failing) : "n/a";
  lines.push(
    `- **CLI conformance: ${cli.passing}/${cli.total} pass** against ${bin} ` +
      `(pass delta ${passDelta}, fail delta ${failDelta}).`,
  );
  lines.push("");
  lines.push("| File | Passing | Failing | Skipped |");
  lines.push("| --- | --- | --- | --- |");
  for (const f of cli.files ?? []) {
    lines.push(`| ${f.file} | ${f.passing} | ${f.failing} | ${f.skipped} |`);
  }
  lines.push("");
  lines.push(
    "The four repointed coding-agent CLI test files spawn the compiled pidgin " +
      "binary via `$PIDGIN_BIN` instead of pi's own `cli.ts`. This is a separate " +
      "signal from the module smoke table and is never folded into the per-package " +
      "Native count.",
  );
}

function main() {
  const current = readMaybe(currentPath);
  const baseline = readMaybe(baselinePath);

  const lines = [];

  if (!current) {
    lines.push("## Conformance smoke");
    lines.push("");
    lines.push(
      `No fresh conformance results were produced (could not read \`${currentPath}\`).`,
    );
    lines.push("");
    lines.push(
      "The smoke run is non-gating; see the job logs for why results are missing.",
    );
    process.stdout.write(lines.join("\n") + "\n");
    return;
  }

  const packages = Object.keys(current.by_package ?? {}).sort();

  lines.push(`## Conformance smoke: ${packages.join(" + ")}`);
  lines.push("");

  const piSha = current.pi_sha ?? "unknown";
  const nativeModules = current.manifest_native_modules ?? 0;
  lines.push(`- pi_sha: \`${piSha}\``);
  lines.push(`- manifest_native_modules: ${nativeModules}`);
  lines.push("");

  lines.push(
    "Headline is **rust-backed**: passing cases in files whose module-under-test is a " +
      "native (Rust addon) module. Raw all-pass is shown secondary — it is inflated by " +
      "unflipped TypeScript that passes without touching any Rust.",
  );
  lines.push("");
  lines.push(
    "| Package | rust-backed | Native modules | raw pass (secondary) | Failing | Skipped |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- |");

  const sumCur = { rustBackedPassing: 0, total: 0, passing: 0, failing: 0, skipped: 0, native: 0 };
  const compact = [];

  for (const pkg of packages) {
    const cur = pkgStats(current, pkg);
    if (!cur) continue;
    const rustCell = `${cur.rustBackedPassing}/${cur.total} (${cur.rustBackedPercent.toFixed(1)}%)`;
    lines.push(
      `| ${pkg} | **${rustCell}** | ${cur.native} | ${cur.passing}/${cur.total} | ${cur.failing} | ${cur.skipped} |`,
    );
    compact.push(`${pkg}: ${rustCell}`);
    sumCur.rustBackedPassing += cur.rustBackedPassing;
    sumCur.total += cur.total;
    sumCur.passing += cur.passing;
    sumCur.failing += cur.failing;
    sumCur.skipped += cur.skipped;
    sumCur.native += cur.native;
  }

  const rollupPercent = sumCur.total > 0 ? ((sumCur.rustBackedPassing / sumCur.total) * 100).toFixed(1) : "0.0";
  const rollupCell = `${sumCur.rustBackedPassing}/${sumCur.total} (${rollupPercent}%)`;
  lines.push(
    `| smoke total | **${rollupCell}** | ${sumCur.native} | ${sumCur.passing}/${sumCur.total} | ${sumCur.failing} | ${sumCur.skipped} |`,
  );
  lines.push("");
  if (compact.length > 0) {
    lines.push(compact.join(" · "));
    lines.push("");
  }
  lines.push(
    "rust-backed = passing / total tests run, per the manifest's per-native-row `tests` " +
      "lists. The Native modules column counts modules served by the Rust addon. This is the " +
      `${packages.join("+")} smoke subset; the full baseline lives in committed ` +
      "`conformance.json`.",
  );
  lines.push("");

  attributionSection(lines);

  cliSection(lines, current, baseline);

  process.stdout.write(lines.join("\n") + "\n");
}

main();
