// Builds the markdown body for the conformance sticky PR comment.
//
// Reads two conformance.json documents and compares them like-for-like over the
// packages the CI smoke run actually exercised (agent, ai, tui):
//   argv[2] — fresh results generated by this CI run (default: conformance.json)
//   argv[3] — committed baseline snapshot taken before the run
//
// Prints markdown to stdout. Only the packages present in the fresh results are
// reported, each with its current totals and the passing/failing delta against
// the same package in the baseline. The full five-package baseline stays in the
// committed conformance.json; this comment covers the smoke subset only.
import { readFileSync } from "node:fs";

const currentPath = process.argv[2] || "conformance.json";
const baselinePath = process.argv[3];

function readMaybe(path) {
  if (!path) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

function signed(delta) {
  if (delta > 0) return `+${delta}`;
  if (delta < 0) return `${delta}`;
  return "±0"; // ±0
}

function pkgStats(doc, pkg) {
  const p = doc?.by_package?.[pkg];
  if (!p) return null;
  return {
    total: p.total ?? 0,
    passing: p.passing ?? 0,
    failing: p.failing ?? 0,
    skipped: p.skipped ?? 0,
    native: p.native ?? 0,
  };
}

function main() {
  const current = readMaybe(currentPath);
  const baseline = readMaybe(baselinePath);

  const lines = [];

  if (!current) {
    lines.push("## Conformance smoke");
    lines.push("");
    lines.push(
      `No fresh conformance results were produced (could not read \`${currentPath}\`).`,
    );
    lines.push("");
    lines.push(
      "The smoke run is non-gating; see the job logs for why results are missing.",
    );
    process.stdout.write(lines.join("\n") + "\n");
    return;
  }

  const packages = Object.keys(current.by_package ?? {}).sort();

  lines.push(`## Conformance smoke: ${packages.join(" + ")}`);
  lines.push("");

  const piSha = current.pi_sha ?? "unknown";
  const nativeModules = current.manifest_native_modules ?? 0;
  lines.push(`- pi_sha: \`${piSha}\``);
  lines.push(`- manifest_native_modules: ${nativeModules}`);
  lines.push("");

  lines.push(
    "| Package | Total | Passing | Failing | Skipped | Native | pass delta | fail delta |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- |");

  const sumCur = { total: 0, passing: 0, failing: 0, skipped: 0, native: 0 };
  const sumBase = { passing: 0, failing: 0 };
  const compact = [];

  for (const pkg of packages) {
    const cur = pkgStats(current, pkg);
    if (!cur) continue;
    const base = pkgStats(baseline, pkg);
    const passDelta = base ? cur.passing - base.passing : null;
    const failDelta = base ? cur.failing - base.failing : null;
    const passCell = passDelta === null ? "n/a" : signed(passDelta);
    const failCell = failDelta === null ? "n/a" : signed(failDelta);
    lines.push(
      `| ${pkg} | ${cur.total} | ${cur.passing} | ${cur.failing} | ${cur.skipped} | ${cur.native} | ${passCell} | ${failCell} |`,
    );
    const nativeNote = cur.native > 0 ? `, ${cur.native} native` : "";
    compact.push(`${pkg}: ${cur.passing}/${cur.total} pass (${passCell})${nativeNote}`);
    sumCur.total += cur.total;
    sumCur.passing += cur.passing;
    sumCur.failing += cur.failing;
    sumCur.skipped += cur.skipped;
    sumCur.native += cur.native;
    if (base) {
      sumBase.passing += base.passing;
      sumBase.failing += base.failing;
    }
  }

  const totalPassDelta = signed(sumCur.passing - sumBase.passing);
  const totalFailDelta = signed(sumCur.failing - sumBase.failing);
  lines.push(
    `| smoke total | ${sumCur.total} | ${sumCur.passing} | ${sumCur.failing} | ${sumCur.skipped} | ${sumCur.native} | ${totalPassDelta} | ${totalFailDelta} |`,
  );
  lines.push("");
  if (compact.length > 0) {
    lines.push(compact.join(" · "));
    lines.push("");
  }
  lines.push(
    "Deltas compare this run against the committed baseline for the same packages. " +
      "The Native column counts modules served by the Rust addon (from the conformance " +
      `manifest). This is the ${packages.join("+")} smoke subset; the full five-package ` +
      "baseline lives in committed `conformance.json`.",
  );

  process.stdout.write(lines.join("\n") + "\n");
}

main();
