//! JSON wire round-trip tests for the ported boundary types.
//!
//! Every fixture under `tests/fixtures/` is authoritative: generated by
//! `conformance/gen-ai-fixtures.ts` from pi's own source at the pinned submodule
//! commit `3da591ab`. Content blocks, messages, and the stream event union come
//! from executing pi's faux builders and real streaming loop
//! (`providers/faux.ts`); the cost cases come from executing pi's `calculateCost`
//! (`models.ts`); the remaining literals are type-checked against pi's exported
//! `types.ts` interfaces. Regenerate with `bun run conformance/gen-ai-fixtures.ts`.
//!
//! Each test deserializes a fixture into the atilla type, re-serializes, and
//! asserts the JSON matches. Comparison is numeric-aware: a whole number written
//! as `3` in pi's output and re-emitted as `3.0` by an `f64` field is treated as
//! equal, since the two are the same JSON number and the napi boundary converts
//! `f64` back to a JS number regardless. Structure, field names, casing, and tag
//! values are still compared exactly.

use std::fs;
use std::path::PathBuf;

use atilla_ai::{
    calculate_cost, AnthropicMessagesCompat, AssistantMessage, AssistantMessageEvent, ContentBlock,
    Message, Model, Usage, UsageCost,
};
use serde::{de::DeserializeOwned, Serialize};
use serde_json::Value;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn read_fixture(name: &str) -> Value {
    let raw = fs::read_to_string(fixture_path(name))
        .unwrap_or_else(|e| panic!("read fixture {name}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse fixture {name}: {e}"))
}

/// Numeric-aware deep JSON equality (see module docs for the `3` vs `3.0` case).
fn json_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => match (x.as_f64(), y.as_f64()) {
            (Some(fx), Some(fy)) => fx == fy,
            _ => x == y,
        },
        (Value::Array(xs), Value::Array(ys)) => {
            xs.len() == ys.len() && xs.iter().zip(ys).all(|(x, y)| json_eq(x, y))
        }
        (Value::Object(xs), Value::Object(ys)) => {
            xs.len() == ys.len()
                && xs
                    .iter()
                    .all(|(k, x)| ys.get(k).is_some_and(|y| json_eq(x, y)))
        }
        _ => a == b,
    }
}

/// Deserialize `name` into `T`, re-serialize, and assert the JSON round-trips.
fn assert_roundtrip<T: Serialize + DeserializeOwned>(name: &str) -> T {
    let original = read_fixture(name);
    let value: T = serde_json::from_value(original.clone()).unwrap_or_else(|e| {
        panic!(
            "deserialize {name} into {}: {e}",
            std::any::type_name::<T>()
        )
    });
    let reserialized =
        serde_json::to_value(&value).unwrap_or_else(|e| panic!("serialize {name}: {e}"));
    assert!(
        json_eq(&original, &reserialized),
        "round-trip mismatch for {name}\n original:     {original:#}\n reserialized: {reserialized:#}",
    );
    value
}

// --- Content blocks -------------------------------------------------------

#[test]
fn content_blocks_roundtrip() {
    assert_roundtrip::<ContentBlock>("content_text.json");
    assert_roundtrip::<ContentBlock>("content_text_signature.json");
    assert_roundtrip::<ContentBlock>("content_thinking.json");
    assert_roundtrip::<ContentBlock>("content_thinking_redacted.json");
    assert_roundtrip::<ContentBlock>("content_image.json");
    assert_roundtrip::<ContentBlock>("content_toolcall.json");
    assert_roundtrip::<ContentBlock>("content_toolcall_thought.json");
}

#[test]
fn content_block_variants_parse_to_expected() {
    let text = assert_roundtrip::<ContentBlock>("content_text.json");
    assert!(matches!(text, ContentBlock::Text { .. }));

    let image = assert_roundtrip::<ContentBlock>("content_image.json");
    match image {
        ContentBlock::Image { data, mime_type } => {
            assert_eq!(mime_type, "image/png");
            assert_eq!(data, "aGVsbG8=");
        }
        other => panic!("expected image, got {other:?}"),
    }

    let call = assert_roundtrip::<ContentBlock>("content_toolcall.json");
    match call {
        ContentBlock::ToolCall {
            id,
            name,
            arguments,
            ..
        } => {
            assert_eq!(id, "tool-fixed-1");
            assert_eq!(name, "echo");
            assert_eq!(arguments["text"], Value::String("hi".into()));
        }
        other => panic!("expected tool call, got {other:?}"),
    }
}

#[test]
fn unknown_content_block_is_caught() {
    // A provider block type we do not model must land in the `Unknown` catch-all
    // rather than failing deserialization (the forward-compat boundary contract).
    let original = read_fixture("content_unknown.json");
    let block: ContentBlock = serde_json::from_value(original).expect("unknown block deserializes");
    assert!(matches!(block, ContentBlock::Unknown));
}

// --- Messages -------------------------------------------------------------

#[test]
fn messages_roundtrip() {
    let user_string = assert_roundtrip::<Message>("message_user_string.json");
    assert!(matches!(user_string, Message::User(_)));

    let user_blocks = assert_roundtrip::<Message>("message_user_blocks.json");
    assert!(matches!(user_blocks, Message::User(_)));

    let tool_result = assert_roundtrip::<Message>("message_tool_result.json");
    assert!(matches!(tool_result, Message::ToolResult(_)));

    // The assistant message round-trips both as a bare AssistantMessage (its
    // shape inside stream events) and through the Message union.
    let assistant = assert_roundtrip::<AssistantMessage>("message_assistant.json");
    assert_eq!(assistant.content.len(), 3);
    let via_union = assert_roundtrip::<Message>("message_assistant.json");
    assert!(matches!(via_union, Message::Assistant(_)));
}

// --- Usage ----------------------------------------------------------------

#[test]
fn usage_roundtrips() {
    let usage = assert_roundtrip::<Usage>("usage.json");
    assert_eq!(usage.cache_write_1h, Some(40));
    assert_eq!(usage.reasoning, Some(120));
    assert_eq!(usage.total_tokens, 1800);
}

// --- Streaming event union ------------------------------------------------

#[test]
fn stream_events_roundtrip() {
    let events = assert_roundtrip::<Vec<AssistantMessageEvent>>("events.json");
    // The driven faux stream emits the full lifecycle for a thinking + tool call
    // + text response.
    let kinds: Vec<&str> = events
        .iter()
        .map(|e| match e {
            AssistantMessageEvent::Start { .. } => "start",
            AssistantMessageEvent::TextStart { .. } => "text_start",
            AssistantMessageEvent::TextDelta { .. } => "text_delta",
            AssistantMessageEvent::TextEnd { .. } => "text_end",
            AssistantMessageEvent::ThinkingStart { .. } => "thinking_start",
            AssistantMessageEvent::ThinkingDelta { .. } => "thinking_delta",
            AssistantMessageEvent::ThinkingEnd { .. } => "thinking_end",
            AssistantMessageEvent::ToolcallStart { .. } => "toolcall_start",
            AssistantMessageEvent::ToolcallDelta { .. } => "toolcall_delta",
            AssistantMessageEvent::ToolcallEnd { .. } => "toolcall_end",
            AssistantMessageEvent::Done { .. } => "done",
            AssistantMessageEvent::Error { .. } => "error",
        })
        .collect();
    assert_eq!(
        kinds,
        [
            "start",
            "thinking_start",
            "thinking_delta",
            "thinking_end",
            "toolcall_start",
            "toolcall_delta",
            "toolcall_end",
            "text_start",
            "text_delta",
            "text_end",
            "done",
        ]
    );
}

#[test]
fn error_event_roundtrips() {
    let event = assert_roundtrip::<AssistantMessageEvent>("event_error.json");
    match event {
        AssistantMessageEvent::Error { error, .. } => {
            assert_eq!(error.error_message.as_deref(), Some("kaboom"));
        }
        other => panic!("expected error event, got {other:?}"),
    }
}

// --- Model ----------------------------------------------------------------

#[test]
fn model_with_compat_roundtrips() {
    let model = assert_roundtrip::<Model<AnthropicMessagesCompat>>("model.json");
    assert_eq!(model.id, "claude-opus-4-8");
    assert_eq!(model.api, "anthropic-messages");
    let compat = model.compat.expect("compat present");
    assert_eq!(compat.supports_temperature, Some(false));
    assert_eq!(compat.supports_eager_tool_input_streaming, Some(true));
    let tiers = model.cost.tiers.expect("tiers present");
    assert_eq!(tiers.len(), 1);
    assert_eq!(tiers[0].input_tokens_above, 200000);
}

// --- calculateCost --------------------------------------------------------

#[derive(serde::Deserialize)]
struct CostCase {
    name: String,
    model: Model<AnthropicMessagesCompat>,
    usage: Usage,
    cost: UsageCost,
}

#[test]
fn calculate_cost_matches_pi() {
    let cases: Vec<CostCase> =
        serde_json::from_value(read_fixture("cost_cases.json")).expect("parse cost cases");
    assert!(!cases.is_empty());
    for case in &cases {
        let computed = calculate_cost(&case.model, &case.usage);
        // Bit-exact match against pi's calculateCost output: the arithmetic is a
        // direct port, so the f64 results are identical.
        assert_eq!(
            computed, case.cost,
            "cost mismatch for case '{}'\n computed: {computed:?}\n expected: {:?}",
            case.name, case.cost,
        );
    }
}
