//! GENERATED by fluessig bindgen from pidgin.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated by fluessig; edit the schema instead
#![allow(unused_imports)]
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use napi::bindgen_prelude::Result;
use napi_derive::napi;

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// Result of [`slice_with_width`]; serialized to `{ text, width }`.
#[napi(object)]
#[derive(Clone)]
pub struct SliceWithWidth {
    pub text: String,
    pub width: i32,
}

/// Result of [`extract_segments`]; serialized to
/// `{ before, beforeWidth, after, afterWidth }`.
#[napi(object)]
#[derive(Clone)]
pub struct ExtractSegmentsResult {
    pub before: String,
    pub before_width: i32,
    pub after: String,
    pub after_width: i32,
}

/// The `Pidgin` contract — implement over the engine in `crate::core_impl`.
pub trait PidginCore: Sized + Send + Sync + 'static {
    fn version() -> String;
    fn expand_path(file_path: String) -> anyhow::Result<String>;
    fn resolve_to_cwd(file_path: String, cwd: String) -> anyhow::Result<String>;
    fn path_try_macos_screenshot_path(file_path: String) -> String;
    fn path_try_nfd_variant(file_path: String) -> String;
    fn path_try_curly_quote_variant(file_path: String) -> String;
    fn parse_key(data: String) -> Option<String>;
    fn matches_key(data: String, key_id: String) -> bool;
    fn decode_kitty_printable(data: String) -> Option<String>;
    fn decode_printable_key(data: String) -> Option<String>;
    fn set_kitty_protocol_active(active: bool) -> ();
    fn visible_width(s: String) -> i32;
    fn normalize_terminal_output(s: String) -> String;
    fn truncate_to_width(text: String, max_width: i32, ellipsis: String, pad: bool) -> String;
    fn wrap_text_with_ansi(text: String, width: i32) -> Vec<String>;
    fn slice_with_width(line: String, start_col: i32, length: i32, strict: bool) -> SliceWithWidth;
    fn extract_segments(
        line: String,
        before_end: i32,
        after_start: i32,
        after_len: i32,
        strict_after: bool,
    ) -> ExtractSegmentsResult;
}

/// Returns the crate version. Proves the native addon builds and loads.
///
/// Exported to JavaScript as `pidginNativeVersion`.
#[napi(js_name = "pidginNativeVersion")]
pub fn version() -> String {
    <crate::core_impl::PidginImpl as PidginCore>::version()
}

/// `expandPath` (core/tools/path-utils.ts): fold unicode spaces, strip a leading
/// `@`, expand `~`, convert `file://`. Errors cross as thrown JS errors.
#[napi(js_name = "expandPath")]
pub fn expand_path(file_path: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::expand_path(file_path).map_err(err)
}

/// `resolveToCwd` (core/tools/path-utils.ts): resolve `file_path` against `cwd`.
/// Errors cross as thrown JS errors (pi's `resolvePath` throws on bad input).
#[napi(js_name = "resolveToCwd")]
pub fn resolve_to_cwd(file_path: String, cwd: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::resolve_to_cwd(file_path, cwd).map_err(err)
}

/// Private pi transform `tryMacOSScreenshotPath`, exposed so the shim's
/// `resolveReadPath` can rebuild pi's fallback ordering natively.
#[napi(js_name = "pathTryMacosScreenshotPath")]
pub fn path_try_macos_screenshot_path(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_macos_screenshot_path(file_path)
}

/// Private pi transform `tryNFDVariant`, exposed for the shim's `resolveReadPath`.
#[napi(js_name = "pathTryNfdVariant")]
pub fn path_try_nfd_variant(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_nfd_variant(file_path)
}

/// Private pi transform `tryCurlyQuoteVariant`, exposed for the shim's
/// `resolveReadPath`.
#[napi(js_name = "pathTryCurlyQuoteVariant")]
pub fn path_try_curly_quote_variant(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_curly_quote_variant(file_path)
}

/// `parseKey` (keys.ts): decode a raw key sequence to its canonical id.
#[napi(js_name = "parseKey")]
pub fn parse_key(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::parse_key(data)
}

/// `matchesKey` (keys.ts): does `data` decode to `key_id`?
#[napi(js_name = "matchesKey")]
pub fn matches_key(data: String, key_id: String) -> bool {
    <crate::core_impl::PidginImpl as PidginCore>::matches_key(data, key_id)
}

/// `decodeKittyPrintable` (keys.ts): printable char from a kitty sequence.
#[napi(js_name = "decodeKittyPrintable")]
pub fn decode_kitty_printable(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::decode_kitty_printable(data)
}

/// `decodePrintableKey` (keys.ts): printable char from a key sequence.
#[napi(js_name = "decodePrintableKey")]
pub fn decode_printable_key(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::decode_printable_key(data)
}

/// `setKittyProtocolActive` (keys.ts): toggle kitty-protocol decoding.
#[napi(js_name = "setKittyProtocolActive")]
pub fn set_kitty_protocol_active(active: bool) -> () {
    <crate::core_impl::PidginImpl as PidginCore>::set_kitty_protocol_active(active)
}

/// `visibleWidth` (utils.ts): display width of a string, ANSI-aware.
#[napi(js_name = "visibleWidth")]
pub fn visible_width(s: String) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::visible_width(s)
}

/// `normalizeTerminalOutput` (utils.ts): canonicalize ANSI/control sequences.
#[napi(js_name = "normalizeTerminalOutput")]
pub fn normalize_terminal_output(s: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::normalize_terminal_output(s)
}

/// `truncateToWidth` (utils.ts): clip to `max_width` columns, ANSI-preserving.
#[napi(js_name = "truncateToWidth")]
pub fn truncate_to_width(text: String, max_width: i32, ellipsis: String, pad: bool) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::truncate_to_width(text, max_width, ellipsis, pad)
}

/// `wrapTextWithAnsi` (utils.ts): hard-wrap to `width` columns, ANSI-preserving.
#[napi(js_name = "wrapTextWithAnsi")]
pub fn wrap_text_with_ansi(text: String, width: i32) -> Vec<String> {
    <crate::core_impl::PidginImpl as PidginCore>::wrap_text_with_ansi(text, width)
}

/// `sliceWithWidth` (utils.ts): slice `length` columns from `start_col`.
#[napi(js_name = "sliceWithWidth")]
pub fn slice_with_width(line: String, start_col: i32, length: i32, strict: bool) -> SliceWithWidth {
    <crate::core_impl::PidginImpl as PidginCore>::slice_with_width(line, start_col, length, strict)
}

/// `extractSegments` (utils.ts): single-pass before/after overlay split.
#[napi(js_name = "extractSegments")]
pub fn extract_segments(
    line: String,
    before_end: i32,
    after_start: i32,
    after_len: i32,
    strict_after: bool,
) -> ExtractSegmentsResult {
    <crate::core_impl::PidginImpl as PidginCore>::extract_segments(
        line,
        before_end,
        after_start,
        after_len,
        strict_after,
    )
}
