//! GENERATED by fluessig bindgen from pidgin.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated by fluessig; edit the schema instead
#![allow(unused_imports)]
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use napi::bindgen_prelude::Result;
use napi_derive::napi;
use std::sync::Arc;

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// Result of [`slice_with_width`]; serialized to `{ text, width }`.
#[napi(object)]
#[derive(Clone)]
pub struct SliceWithWidth {
    pub text: String,
    pub width: i32,
}

/// Result of [`extract_segments`]; serialized to
/// `{ before, beforeWidth, after, afterWidth }`.
#[napi(object)]
#[derive(Clone)]
pub struct ExtractSegmentsResult {
    pub before: String,
    pub before_width: i32,
    pub after: String,
    pub after_width: i32,
}

/// The `Pidgin` contract — implement over the engine in `crate::core_impl`.
pub trait PidginCore: Sized + Send + Sync + 'static {
    fn version() -> String;
    fn expand_path(file_path: String) -> anyhow::Result<String>;
    fn resolve_to_cwd(file_path: String, cwd: String) -> anyhow::Result<String>;
    fn path_try_macos_screenshot_path(file_path: String) -> String;
    fn path_try_nfd_variant(file_path: String) -> String;
    fn path_try_curly_quote_variant(file_path: String) -> String;
    fn parse_key(data: String) -> Option<String>;
    fn matches_key(data: String, key_id: String) -> bool;
    fn decode_kitty_printable(data: String) -> Option<String>;
    fn decode_printable_key(data: String) -> Option<String>;
    fn set_kitty_protocol_active(active: bool) -> ();
    fn visible_width(s: String) -> i32;
    fn normalize_terminal_output(s: String) -> String;
    fn truncate_to_width(text: String, max_width: i32, ellipsis: String, pad: bool) -> String;
    fn wrap_text_with_ansi(text: String, width: i32) -> Vec<String>;
    fn slice_with_width(line: String, start_col: i32, length: i32, strict: bool) -> SliceWithWidth;
    fn extract_segments(
        line: String,
        before_end: i32,
        after_start: i32,
        after_len: i32,
        strict_after: bool,
    ) -> ExtractSegmentsResult;
    fn find_word_backward(text: String, cursor: i32) -> i32;
    fn find_word_forward(text: String, cursor: i32) -> i32;
}

/// The `KeybindingsManagerCore` contract — implement over the engine in `crate::core_impl`.
pub trait KeybindingsManagerCoreCore: Sized + Send + Sync + 'static {
    fn new(definitions_json: String, user_bindings_json: String) -> anyhow::Result<Self>;
    fn matches(&self, data: String, keybinding: String) -> bool;
    fn get_keys(&self, keybinding: String) -> Vec<String>;
    fn get_conflicts_json(&self) -> anyhow::Result<String>;
    fn get_resolved_bindings_json(&self) -> anyhow::Result<String>;
}

/// The `CommandCore` contract — implement over the engine in `crate::core_impl`.
pub trait CommandCoreCore: Sized + Send + Sync + 'static {
    fn new(op: String, params_json: String) -> anyhow::Result<Self>;
    fn start(&self) -> anyhow::Result<String>;
    fn advance(&self, output_json: String) -> anyhow::Result<String>;
}

/// The `FauxCore` contract — implement over the engine in `crate::core_impl`.
pub trait FauxCoreCore: Sized + Send + Sync + 'static {
    fn new(options_json: String) -> anyhow::Result<Self>;
    fn set_now_ms(&self, now_ms: i64) -> ();
    fn api(&self) -> String;
    fn models_json(&self) -> anyhow::Result<String>;
    fn get_model_json(&self, id: Option<String>) -> anyhow::Result<Option<String>>;
    fn bump_call_count(&self) -> i64;
    fn call_count(&self) -> i64;
    fn stream_resolved(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
        message_json: String,
        aborted: bool,
    ) -> anyhow::Result<String>;
    fn empty_queue_result(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
    ) -> anyhow::Result<String>;
}

/// Returns the crate version. Proves the native addon builds and loads.
///
/// Exported to JavaScript as `pidginNativeVersion`.
#[napi(js_name = "pidginNativeVersion")]
pub fn version() -> String {
    <crate::core_impl::PidginImpl as PidginCore>::version()
}

/// `expandPath` (core/tools/path-utils.ts): fold unicode spaces, strip a leading
/// `@`, expand `~`, convert `file://`. Errors cross as thrown JS errors.
#[napi(js_name = "expandPath")]
pub fn expand_path(file_path: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::expand_path(file_path).map_err(err)
}

/// `resolveToCwd` (core/tools/path-utils.ts): resolve `file_path` against `cwd`.
/// Errors cross as thrown JS errors (pi's `resolvePath` throws on bad input).
#[napi(js_name = "resolveToCwd")]
pub fn resolve_to_cwd(file_path: String, cwd: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::resolve_to_cwd(file_path, cwd).map_err(err)
}

/// Private pi transform `tryMacOSScreenshotPath`, exposed so the shim's
/// `resolveReadPath` can rebuild pi's fallback ordering natively.
#[napi(js_name = "pathTryMacosScreenshotPath")]
pub fn path_try_macos_screenshot_path(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_macos_screenshot_path(file_path)
}

/// Private pi transform `tryNFDVariant`, exposed for the shim's `resolveReadPath`.
#[napi(js_name = "pathTryNfdVariant")]
pub fn path_try_nfd_variant(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_nfd_variant(file_path)
}

/// Private pi transform `tryCurlyQuoteVariant`, exposed for the shim's
/// `resolveReadPath`.
#[napi(js_name = "pathTryCurlyQuoteVariant")]
pub fn path_try_curly_quote_variant(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_curly_quote_variant(file_path)
}

/// `parseKey` (keys.ts): decode a raw key sequence to its canonical id.
#[napi(js_name = "parseKey")]
pub fn parse_key(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::parse_key(data)
}

/// `matchesKey` (keys.ts): does `data` decode to `key_id`?
#[napi(js_name = "matchesKey")]
pub fn matches_key(data: String, key_id: String) -> bool {
    <crate::core_impl::PidginImpl as PidginCore>::matches_key(data, key_id)
}

/// `decodeKittyPrintable` (keys.ts): printable char from a kitty sequence.
#[napi(js_name = "decodeKittyPrintable")]
pub fn decode_kitty_printable(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::decode_kitty_printable(data)
}

/// `decodePrintableKey` (keys.ts): printable char from a key sequence.
#[napi(js_name = "decodePrintableKey")]
pub fn decode_printable_key(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::decode_printable_key(data)
}

/// `setKittyProtocolActive` (keys.ts): toggle kitty-protocol decoding.
#[napi(js_name = "setKittyProtocolActive")]
pub fn set_kitty_protocol_active(active: bool) -> () {
    <crate::core_impl::PidginImpl as PidginCore>::set_kitty_protocol_active(active)
}

/// `visibleWidth` (utils.ts): display width of a string, ANSI-aware.
#[napi(js_name = "visibleWidth")]
pub fn visible_width(s: String) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::visible_width(s)
}

/// `normalizeTerminalOutput` (utils.ts): canonicalize ANSI/control sequences.
#[napi(js_name = "normalizeTerminalOutput")]
pub fn normalize_terminal_output(s: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::normalize_terminal_output(s)
}

/// `truncateToWidth` (utils.ts): clip to `max_width` columns, ANSI-preserving.
#[napi(js_name = "truncateToWidth")]
pub fn truncate_to_width(text: String, max_width: i32, ellipsis: String, pad: bool) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::truncate_to_width(text, max_width, ellipsis, pad)
}

/// `wrapTextWithAnsi` (utils.ts): hard-wrap to `width` columns, ANSI-preserving.
#[napi(js_name = "wrapTextWithAnsi")]
pub fn wrap_text_with_ansi(text: String, width: i32) -> Vec<String> {
    <crate::core_impl::PidginImpl as PidginCore>::wrap_text_with_ansi(text, width)
}

/// `sliceWithWidth` (utils.ts): slice `length` columns from `start_col`.
#[napi(js_name = "sliceWithWidth")]
pub fn slice_with_width(line: String, start_col: i32, length: i32, strict: bool) -> SliceWithWidth {
    <crate::core_impl::PidginImpl as PidginCore>::slice_with_width(line, start_col, length, strict)
}

/// `extractSegments` (utils.ts): single-pass before/after overlay split.
#[napi(js_name = "extractSegments")]
pub fn extract_segments(
    line: String,
    before_end: i32,
    after_start: i32,
    after_len: i32,
    strict_after: bool,
) -> ExtractSegmentsResult {
    <crate::core_impl::PidginImpl as PidginCore>::extract_segments(
        line,
        before_end,
        after_start,
        after_len,
        strict_after,
    )
}

/// `findWordBackward` (word-navigation.ts), default segmentation: cursor after
/// moving one word backward from `cursor` (UTF-16 index).
#[napi(js_name = "findWordBackward")]
pub fn find_word_backward(text: String, cursor: i32) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::find_word_backward(text, cursor)
}

/// `findWordForward` (word-navigation.ts), default segmentation: cursor after
/// moving one word forward from `cursor` (UTF-16 index).
#[napi(js_name = "findWordForward")]
pub fn find_word_forward(text: String, cursor: i32) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::find_word_forward(text, cursor)
}

/// The Rust-backed keybindings core, exposed to JavaScript as
/// `KeybindingsManagerCore`.
#[napi]
pub struct KeybindingsManagerCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::KeybindingsManagerCoreImpl>,
}

#[napi]
impl KeybindingsManagerCore {
    /// Build a core from pi's `definitions`/`userBindings`, each JSON-encoded as
    /// an ordered array (`[{ id, defaultKeys, description? }]` and
    /// `[{ id, keys }]`, `keys: null` for an explicit `undefined`).
    #[napi(constructor)]
    pub fn new(definitions_json: String, user_bindings_json: String) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::KeybindingsManagerCoreImpl as KeybindingsManagerCoreCore>::new(
                    definitions_json,
                    user_bindings_json,
                )
                .map_err(err)?,
            ),
        })
    }
    /// pi's `matches(data, keybinding)`: does `data` match any bound key?
    #[napi(js_name = "matches")]
    pub fn matches(&self, data: String, keybinding: String) -> bool {
        self.core.matches(data, keybinding)
    }
    /// pi's `getKeys(keybinding)`: the keys bound to `keybinding` (empty if
    /// unknown).
    #[napi(js_name = "getKeys")]
    pub fn get_keys(&self, keybinding: String) -> Vec<String> {
        self.core.get_keys(keybinding)
    }
    /// pi's `getConflicts()` as JSON: an ordered array of
    /// `{ key, keybindings }`.
    #[napi(js_name = "getConflictsJson")]
    pub fn get_conflicts_json(&self) -> Result<String> {
        self.core.get_conflicts_json().map_err(err)
    }
    /// pi's `getResolvedBindings()` as JSON: an ordered array of `[id, keys]`
    /// pairs, in definition order. The shim rebuilds pi's `key | key[]` shape.
    #[napi(js_name = "getResolvedBindingsJson")]
    pub fn get_resolved_bindings_json(&self) -> Result<String> {
        self.core.get_resolved_bindings_json().map_err(err)
    }
}

/// The Rust-backed package-manager command flow, exposed to JavaScript as
/// `CommandCore`. Holds one boxed [`CommandFlowMachine`]; the JS shim drives it
/// through [`CommandCore::start`] / [`CommandCore::advance`].
#[napi]
pub struct CommandCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::CommandCoreImpl>,
}

#[napi]
impl CommandCore {
    /// Build a command core for `op` from its JSON params (see the module docs
    /// for the op catalog and param shapes).
    #[napi(constructor)]
    pub fn new(op: String, params_json: String) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::CommandCoreImpl as CommandCoreCore>::new(op, params_json)
                    .map_err(err)?,
            ),
        })
    }
    /// Plan the first command (or finish immediately). Returns the JSON-encoded
    /// `CommandStep` (`{ type: "run", request }` or `{ type: "done", result }`).
    #[napi(js_name = "start")]
    pub fn start(&self) -> Result<String> {
        self.core.start().map_err(err)
    }
    /// Consume the JSON-encoded `CommandOutput` (`{ code, stdout, stderr }`) of
    /// the last planned command and plan the next one (or finish). Returns the
    /// JSON-encoded `CommandStep`.
    #[napi(js_name = "advance")]
    pub fn advance(&self, output_json: String) -> Result<String> {
        self.core.advance(output_json).map_err(err)
    }
}

/// The Rust-backed faux core, exposed to JavaScript as `FauxCore`.
///
/// The JS `registerFauxProvider` shim constructs one of these, keeps the response
/// queue in JS, and calls [`FauxCore::stream_resolved`] (or
/// [`FauxCore::empty_queue_result`]) per stream. Cross-call state (call count and
/// prompt cache) lives in the wrapped [`FauxProvider`].
#[napi]
pub struct FauxCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::FauxCoreImpl>,
}

#[napi]
impl FauxCore {
    /// Build a faux core from pi's `RegisterFauxProviderOptions`, JSON-encoded.
    #[napi(constructor)]
    pub fn new(options_json: String) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::FauxCoreImpl as FauxCoreCore>::new(options_json).map_err(err)?,
            ),
        })
    }
    /// Set the `now` (epoch milliseconds) the provider reads when stamping the
    /// empty-queue/aborted message timestamps. The JS shim calls this with
    /// `Date.now()` before each stream so those timestamps track JS time.
    #[napi(js_name = "setNowMs")]
    pub fn set_now_ms(&self, now_ms: i64) -> () {
        self.core.set_now_ms(now_ms)
    }
    /// The provider's api id (pi's `core.api`).
    #[napi(js_name = "api")]
    pub fn api(&self) -> String {
        self.core.api()
    }
    /// The model catalog as a JSON array (pi's `core.models`).
    #[napi(js_name = "modelsJson")]
    pub fn models_json(&self) -> Result<String> {
        self.core.models_json().map_err(err)
    }
    /// pi's `getModel()`: the model with `id`, or the first model when `id` is
    /// omitted. Returns `null` when no model matches.
    #[napi(js_name = "getModelJson")]
    pub fn get_model_json(&self, id: Option<String>) -> Result<Option<String>> {
        self.core.get_model_json(id).map_err(err)
    }
    /// Increment and return the call count (pi's `state.callCount++`). The JS
    /// shim calls this before resolving a response factory, matching pi's order.
    #[napi(js_name = "bumpCallCount")]
    pub fn bump_call_count(&self) -> i64 {
        self.core.bump_call_count()
    }
    /// The current call count without incrementing (pi's `state.callCount`).
    #[napi(js_name = "callCount")]
    pub fn call_count(&self) -> i64 {
        self.core.call_count()
    }
    /// Stream an already-resolved response message, returning the
    /// `{ events, message }` result as JSON. The JS shim passes the message it
    /// popped (or computed from a factory); Rust applies pi's clone + usage
    /// estimate + delta streaming. `aborted` reproduces the pre-aborted signal
    /// path (pi's `signal.aborted`).
    #[napi(js_name = "streamResolved")]
    pub fn stream_resolved(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
        message_json: String,
        aborted: bool,
    ) -> Result<String> {
        self.core
            .stream_resolved(
                model_json,
                context_json,
                options_json,
                message_json,
                aborted,
            )
            .map_err(err)
    }
    /// The result pi streams when the response queue is empty (an `error`-stop
    /// message with usage estimated), as JSON.
    #[napi(js_name = "emptyQueueResult")]
    pub fn empty_queue_result(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
    ) -> Result<String> {
        self.core
            .empty_queue_result(model_json, context_json, options_json)
            .map_err(err)
    }
}
