//! GENERATED by fluessig bindgen from pidgin.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated by fluessig; edit the schema instead
#![allow(unused_imports)]
#![allow(clippy::all)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use napi::bindgen_prelude::Result;
use napi_derive::napi;
use std::sync::Arc;

fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// Result of [`slice_with_width`]; serialized to `{ text, width }`.
#[napi(object)]
#[derive(Clone)]
pub struct SliceWithWidth {
    pub text: String,
    pub width: i32,
}

/// Result of [`extract_segments`]; serialized to
/// `{ before, beforeWidth, after, afterWidth }`.
#[napi(object)]
#[derive(Clone)]
pub struct ExtractSegmentsResult {
    pub before: String,
    pub before_width: i32,
    pub after: String,
    pub after_width: i32,
}

/// One event emitted by [`StdinBufferCore::process`], mirroring pi's
/// `"data"` / `"paste"` EventEmitter channels. `kind` is `"data"` for a complete
/// input sequence (one keypress / escape sequence) or `"paste"` for the body of
/// a bracketed paste (markers already stripped); `value` is the payload string.
#[napi(object)]
#[derive(Clone)]
pub struct StdinEventJs {
    pub kind: String,
    pub value: String,
}

/// pi's `SessionCwdIssue`: a resumed session whose stored working directory is
/// gone. `sessionFile` is the persisted session path, `sessionCwd` the stored
/// (now-missing) directory, `fallbackCwd` the directory to continue in.
#[napi(object)]
#[derive(Clone)]
pub struct SessionCwdIssueJs {
    pub session_file: Option<String>,
    pub session_cwd: String,
    pub fallback_cwd: String,
}

/// The `Pidgin` contract — implement over the engine in `crate::core_impl`.
pub trait PidginCore: Sized + Send + Sync + 'static {
    fn version() -> String;
    fn expand_path(file_path: String) -> anyhow::Result<String>;
    fn resolve_to_cwd(file_path: String, cwd: String) -> anyhow::Result<String>;
    fn path_try_macos_screenshot_path(file_path: String) -> String;
    fn path_try_nfd_variant(file_path: String) -> String;
    fn path_try_curly_quote_variant(file_path: String) -> String;
    fn parse_key(data: String) -> Option<String>;
    fn matches_key(data: String, key_id: String) -> bool;
    fn decode_kitty_printable(data: String) -> Option<String>;
    fn decode_printable_key(data: String) -> Option<String>;
    fn set_kitty_protocol_active(active: bool) -> ();
    fn visible_width(s: String) -> i32;
    fn normalize_terminal_output(s: String) -> String;
    fn truncate_to_width(text: String, max_width: i32, ellipsis: String, pad: bool) -> String;
    fn wrap_text_with_ansi(text: String, width: i32) -> Vec<String>;
    fn slice_with_width(line: String, start_col: i32, length: i32, strict: bool) -> SliceWithWidth;
    fn extract_segments(
        line: String,
        before_end: i32,
        after_start: i32,
        after_len: i32,
        strict_after: bool,
    ) -> ExtractSegmentsResult;
    fn find_word_backward(text: String, cursor: i32) -> i32;
    fn find_word_forward(text: String, cursor: i32) -> i32;
    fn parse_git_url(source: String) -> Option<String>;
    fn strip_ansi(value: String) -> String;
    fn get_missing_session_cwd_issue(
        session_cwd: String,
        session_file: Option<String>,
        fallback_cwd: String,
    ) -> Option<SessionCwdIssueJs>;
    fn format_missing_session_cwd_error(issue: SessionCwdIssueJs) -> String;
    fn format_missing_session_cwd_prompt(issue: SessionCwdIssueJs) -> String;
    fn parse_command_args(args_string: String) -> Vec<String>;
    fn substitute_args(content: String, args: Vec<String>) -> String;
    fn get_config_value_env_var_name(config: String) -> Option<String>;
    fn get_config_value_env_var_names(config: String) -> Vec<String>;
    fn is_command_config_value(config: String) -> bool;
    fn clear_config_value_cache() -> ();
    fn normalize_changelog_links(markdown: String, version_json: String) -> anyhow::Result<String>;
    fn compare_package_versions(left_version: String, right_version: String) -> Option<i32>;
    fn is_newer_package_version(candidate_version: String, current_version: String) -> bool;
    fn get_project_trust_parent_path(cwd: String) -> Option<String>;
    fn has_trust_requiring_project_resources(cwd: String, home_dir: String) -> bool;
}

/// The `KeybindingsManagerCore` contract — implement over the engine in `crate::core_impl`.
pub trait KeybindingsManagerCoreCore: Sized + Send + Sync + 'static {
    fn new(definitions_json: String, user_bindings_json: String) -> anyhow::Result<Self>;
    fn matches(&self, data: String, keybinding: String) -> bool;
    fn get_keys(&self, keybinding: String) -> Vec<String>;
    fn get_conflicts_json(&self) -> anyhow::Result<String>;
    fn get_resolved_bindings_json(&self) -> anyhow::Result<String>;
}

/// The `CommandCore` contract — implement over the engine in `crate::core_impl`.
pub trait CommandCoreCore: Sized + Send + Sync + 'static {
    fn new(op: String, params_json: String) -> anyhow::Result<Self>;
    fn start(&self) -> anyhow::Result<String>;
    fn advance(&self, output_json: String) -> anyhow::Result<String>;
}

/// The `FauxCore` contract — implement over the engine in `crate::core_impl`.
pub trait FauxCoreCore: Sized + Send + Sync + 'static {
    fn new(options_json: String) -> anyhow::Result<Self>;
    fn set_now_ms(&self, now_ms: i64) -> ();
    fn api(&self) -> String;
    fn models_json(&self) -> anyhow::Result<String>;
    fn get_model_json(&self, id: Option<String>) -> anyhow::Result<Option<String>>;
    fn bump_call_count(&self) -> i64;
    fn call_count(&self) -> i64;
    fn stream_resolved(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
        message_json: String,
        aborted: bool,
    ) -> anyhow::Result<String>;
    fn empty_queue_result(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
    ) -> anyhow::Result<String>;
}

/// The `StdinBufferCore` contract — implement over the engine in `crate::core_impl`.
pub trait StdinBufferCoreCore: Sized + Send + Sync + 'static {
    fn new(timeout_ms: Option<i64>) -> anyhow::Result<Self>;
    fn process(&self, data: String) -> Vec<StdinEventJs>;
    fn flush(&self) -> Vec<String>;
    fn get_buffer(&self) -> String;
    fn clear(&self) -> ();
}

/// Returns the crate version. Proves the native addon builds and loads.
///
/// Exported to JavaScript as `pidginNativeVersion`.
#[napi(js_name = "pidginNativeVersion")]
pub fn version() -> String {
    <crate::core_impl::PidginImpl as PidginCore>::version()
}

/// `expandPath` (core/tools/path-utils.ts): fold unicode spaces, strip a leading
/// `@`, expand `~`, convert `file://`. Errors cross as thrown JS errors.
#[napi(js_name = "expandPath")]
pub fn expand_path(file_path: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::expand_path(file_path).map_err(err)
}

/// `resolveToCwd` (core/tools/path-utils.ts): resolve `file_path` against `cwd`.
/// Errors cross as thrown JS errors (pi's `resolvePath` throws on bad input).
#[napi(js_name = "resolveToCwd")]
pub fn resolve_to_cwd(file_path: String, cwd: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::resolve_to_cwd(file_path, cwd).map_err(err)
}

/// Private pi transform `tryMacOSScreenshotPath`, exposed so the shim's
/// `resolveReadPath` can rebuild pi's fallback ordering natively.
#[napi(js_name = "pathTryMacosScreenshotPath")]
pub fn path_try_macos_screenshot_path(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_macos_screenshot_path(file_path)
}

/// Private pi transform `tryNFDVariant`, exposed for the shim's `resolveReadPath`.
#[napi(js_name = "pathTryNfdVariant")]
pub fn path_try_nfd_variant(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_nfd_variant(file_path)
}

/// Private pi transform `tryCurlyQuoteVariant`, exposed for the shim's
/// `resolveReadPath`.
#[napi(js_name = "pathTryCurlyQuoteVariant")]
pub fn path_try_curly_quote_variant(file_path: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::path_try_curly_quote_variant(file_path)
}

/// `parseKey` (keys.ts): decode a raw key sequence to its canonical id.
#[napi(js_name = "parseKey")]
pub fn parse_key(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::parse_key(data)
}

/// `matchesKey` (keys.ts): does `data` decode to `key_id`?
#[napi(js_name = "matchesKey")]
pub fn matches_key(data: String, key_id: String) -> bool {
    <crate::core_impl::PidginImpl as PidginCore>::matches_key(data, key_id)
}

/// `decodeKittyPrintable` (keys.ts): printable char from a kitty sequence.
#[napi(js_name = "decodeKittyPrintable")]
pub fn decode_kitty_printable(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::decode_kitty_printable(data)
}

/// `decodePrintableKey` (keys.ts): printable char from a key sequence.
#[napi(js_name = "decodePrintableKey")]
pub fn decode_printable_key(data: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::decode_printable_key(data)
}

/// `setKittyProtocolActive` (keys.ts): toggle kitty-protocol decoding.
#[napi(js_name = "setKittyProtocolActive")]
pub fn set_kitty_protocol_active(active: bool) -> () {
    <crate::core_impl::PidginImpl as PidginCore>::set_kitty_protocol_active(active)
}

/// `visibleWidth` (utils.ts): display width of a string, ANSI-aware.
#[napi(js_name = "visibleWidth")]
pub fn visible_width(s: String) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::visible_width(s)
}

/// `normalizeTerminalOutput` (utils.ts): canonicalize ANSI/control sequences.
#[napi(js_name = "normalizeTerminalOutput")]
pub fn normalize_terminal_output(s: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::normalize_terminal_output(s)
}

/// `truncateToWidth` (utils.ts): clip to `max_width` columns, ANSI-preserving.
#[napi(js_name = "truncateToWidth")]
pub fn truncate_to_width(text: String, max_width: i32, ellipsis: String, pad: bool) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::truncate_to_width(text, max_width, ellipsis, pad)
}

/// `wrapTextWithAnsi` (utils.ts): hard-wrap to `width` columns, ANSI-preserving.
#[napi(js_name = "wrapTextWithAnsi")]
pub fn wrap_text_with_ansi(text: String, width: i32) -> Vec<String> {
    <crate::core_impl::PidginImpl as PidginCore>::wrap_text_with_ansi(text, width)
}

/// `sliceWithWidth` (utils.ts): slice `length` columns from `start_col`.
#[napi(js_name = "sliceWithWidth")]
pub fn slice_with_width(line: String, start_col: i32, length: i32, strict: bool) -> SliceWithWidth {
    <crate::core_impl::PidginImpl as PidginCore>::slice_with_width(line, start_col, length, strict)
}

/// `extractSegments` (utils.ts): single-pass before/after overlay split.
#[napi(js_name = "extractSegments")]
pub fn extract_segments(
    line: String,
    before_end: i32,
    after_start: i32,
    after_len: i32,
    strict_after: bool,
) -> ExtractSegmentsResult {
    <crate::core_impl::PidginImpl as PidginCore>::extract_segments(
        line,
        before_end,
        after_start,
        after_len,
        strict_after,
    )
}

/// `findWordBackward` (word-navigation.ts), default segmentation: cursor after
/// moving one word backward from `cursor` (UTF-16 index).
#[napi(js_name = "findWordBackward")]
pub fn find_word_backward(text: String, cursor: i32) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::find_word_backward(text, cursor)
}

/// `findWordForward` (word-navigation.ts), default segmentation: cursor after
/// moving one word forward from `cursor` (UTF-16 index).
#[napi(js_name = "findWordForward")]
pub fn find_word_forward(text: String, cursor: i32) -> i32 {
    <crate::core_impl::PidginImpl as PidginCore>::find_word_forward(text, cursor)
}

/// `parseGitUrl` (utils/git.ts): parse a git source string into pi's `GitSource`
/// JSON shape (`{ type, repo, host, path, ref?, pinned }`), or `null`. The shim
/// `JSON.parse`s the result.
#[napi(js_name = "parseGitUrl")]
pub fn parse_git_url(source: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::parse_git_url(source)
}

/// `stripAnsi` (utils/ansi.ts): remove ANSI escape sequences (OSC + CSI). The
/// shim keeps pi's non-string `TypeError` guard, so only strings reach here.
#[napi(js_name = "stripAnsi")]
pub fn strip_ansi(value: String) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::strip_ansi(value)
}

/// pi's `getMissingSessionCwdIssue`. Given the source's stored cwd and optional
/// session file (read JS-side from `SessionCwdSource`) plus the fallback cwd,
/// report a [`SessionCwdIssueJs`] when the source is a persisted session whose
/// stored cwd is non-empty and absent on disk; otherwise `None` (pi's
/// `undefined`).
#[napi(js_name = "getMissingSessionCwdIssue")]
pub fn get_missing_session_cwd_issue(
    session_cwd: String,
    session_file: Option<String>,
    fallback_cwd: String,
) -> Option<SessionCwdIssueJs> {
    <crate::core_impl::PidginImpl as PidginCore>::get_missing_session_cwd_issue(
        session_cwd,
        session_file,
        fallback_cwd,
    )
}

/// pi's `formatMissingSessionCwdError`: the human-readable error text for an
/// issue (backs the JS `MissingSessionCwdError` message).
#[napi(js_name = "formatMissingSessionCwdError")]
pub fn format_missing_session_cwd_error(issue: SessionCwdIssueJs) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::format_missing_session_cwd_error(issue)
}

/// pi's `formatMissingSessionCwdPrompt`: the interactive prompt text for an
/// issue.
#[napi(js_name = "formatMissingSessionCwdPrompt")]
pub fn format_missing_session_cwd_prompt(issue: SessionCwdIssueJs) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::format_missing_session_cwd_prompt(issue)
}

/// `parseCommandArgs` (harness/prompt-templates.ts): split an argument string
/// using simple shell-style single and double quotes.
#[napi(js_name = "parseCommandArgs")]
pub fn parse_command_args(args_string: String) -> Vec<String> {
    <crate::core_impl::PidginImpl as PidginCore>::parse_command_args(args_string)
}

/// `substituteArgs` (harness/prompt-templates.ts): substitute prompt-template
/// placeholders (`$1`, `$@`, `$ARGUMENTS`, `${@:N}`, `${@:N:L}`) with args.
#[napi(js_name = "substituteArgs")]
pub fn substitute_args(content: String, args: Vec<String>) -> String {
    <crate::core_impl::PidginImpl as PidginCore>::substitute_args(content, args)
}

/// `getConfigValueEnvVarName` (resolve-config-value.ts): the single env var a
/// value references, or `null` (pi's `undefined`).
#[napi(js_name = "getConfigValueEnvVarName")]
pub fn get_config_value_env_var_name(config: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::get_config_value_env_var_name(config)
}

/// `getConfigValueEnvVarNames` (resolve-config-value.ts): all distinct env var
/// names a value references, in first-seen order.
#[napi(js_name = "getConfigValueEnvVarNames")]
pub fn get_config_value_env_var_names(config: String) -> Vec<String> {
    <crate::core_impl::PidginImpl as PidginCore>::get_config_value_env_var_names(config)
}

/// `isCommandConfigValue` (resolve-config-value.ts): whether a value is a
/// `!`-prefixed shell command.
#[napi(js_name = "isCommandConfigValue")]
pub fn is_command_config_value(config: String) -> bool {
    <crate::core_impl::PidginImpl as PidginCore>::is_command_config_value(config)
}

/// `clearConfigValueCache` (resolve-config-value.ts): clear the process-lifetime
/// `!command` result cache.
#[napi(js_name = "clearConfigValueCache")]
pub fn clear_config_value_cache() -> () {
    <crate::core_impl::PidginImpl as PidginCore>::clear_config_value_cache()
}

/// `normalizeChangelogLinks` (utils/changelog.ts): rewrite inline markdown links
/// for a release. `version_json` is the JSON-serialized `string | ChangelogEntry`
/// the shim passes; a bare JSON string is a raw version, a JSON object is a
/// `ChangelogEntry`.
#[napi(js_name = "normalizeChangelogLinks")]
pub fn normalize_changelog_links(markdown: String, version_json: String) -> Result<String> {
    <crate::core_impl::PidginImpl as PidginCore>::normalize_changelog_links(markdown, version_json)
        .map_err(err)
}

/// `comparePackageVersions` (utils/version-check.ts): compare two semver
/// strings, mapping `Ordering` to `-1`/`0`/`1`. `None` (incomparable) crosses as
/// JS `null`; the shim converts it to `undefined` to match pi's `number |
/// undefined`.
#[napi(js_name = "comparePackageVersions")]
pub fn compare_package_versions(left_version: String, right_version: String) -> Option<i32> {
    <crate::core_impl::PidginImpl as PidginCore>::compare_package_versions(
        left_version,
        right_version,
    )
}

/// `isNewerPackageVersion` (utils/version-check.ts): is `candidate` strictly
/// newer than `current`?
#[napi(js_name = "isNewerPackageVersion")]
pub fn is_newer_package_version(candidate_version: String, current_version: String) -> bool {
    <crate::core_impl::PidginImpl as PidginCore>::is_newer_package_version(
        candidate_version,
        current_version,
    )
}

/// `getProjectTrustParentPath` (trust-manager.ts): the nearest ancestor path, or
/// `null` at a filesystem root (pi's `undefined`).
#[napi(js_name = "getProjectTrustParentPath")]
pub fn get_project_trust_parent_path(cwd: String) -> Option<String> {
    <crate::core_impl::PidginImpl as PidginCore>::get_project_trust_parent_path(cwd)
}

/// `hasTrustRequiringProjectResources` (trust-manager.ts): whether `cwd` carries
/// project-local resources that must be gated by trust. The shim passes pi's
/// `process.env.HOME || homedir()` as `home_dir`.
#[napi(js_name = "hasTrustRequiringProjectResources")]
pub fn has_trust_requiring_project_resources(cwd: String, home_dir: String) -> bool {
    <crate::core_impl::PidginImpl as PidginCore>::has_trust_requiring_project_resources(
        cwd, home_dir,
    )
}

/// The Rust-backed keybindings core, exposed to JavaScript as
/// `KeybindingsManagerCore`.
#[napi]
pub struct KeybindingsManagerCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::KeybindingsManagerCoreImpl>,
}

#[napi]
impl KeybindingsManagerCore {
    /// Build a core from pi's `definitions`/`userBindings`, each JSON-encoded as
    /// an ordered array (`[{ id, defaultKeys, description? }]` and
    /// `[{ id, keys }]`, `keys: null` for an explicit `undefined`).
    #[napi(constructor)]
    pub fn new(definitions_json: String, user_bindings_json: String) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::KeybindingsManagerCoreImpl as KeybindingsManagerCoreCore>::new(
                    definitions_json,
                    user_bindings_json,
                )
                .map_err(err)?,
            ),
        })
    }
    /// pi's `matches(data, keybinding)`: does `data` match any bound key?
    #[napi(js_name = "matches")]
    pub fn matches(&self, data: String, keybinding: String) -> bool {
        self.core.matches(data, keybinding)
    }
    /// pi's `getKeys(keybinding)`: the keys bound to `keybinding` (empty if
    /// unknown).
    #[napi(js_name = "getKeys")]
    pub fn get_keys(&self, keybinding: String) -> Vec<String> {
        self.core.get_keys(keybinding)
    }
    /// pi's `getConflicts()` as JSON: an ordered array of
    /// `{ key, keybindings }`.
    #[napi(js_name = "getConflictsJson")]
    pub fn get_conflicts_json(&self) -> Result<String> {
        self.core.get_conflicts_json().map_err(err)
    }
    /// pi's `getResolvedBindings()` as JSON: an ordered array of `[id, keys]`
    /// pairs, in definition order. The shim rebuilds pi's `key | key[]` shape.
    #[napi(js_name = "getResolvedBindingsJson")]
    pub fn get_resolved_bindings_json(&self) -> Result<String> {
        self.core.get_resolved_bindings_json().map_err(err)
    }
}

/// The Rust-backed package-manager command flow, exposed to JavaScript as
/// `CommandCore`. Holds one boxed [`CommandFlowMachine`]; the JS shim drives it
/// through [`CommandCore::start`] / [`CommandCore::advance`].
#[napi]
pub struct CommandCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::CommandCoreImpl>,
}

#[napi]
impl CommandCore {
    /// Build a command core for `op` from its JSON params (see the module docs
    /// for the op catalog and param shapes).
    #[napi(constructor)]
    pub fn new(op: String, params_json: String) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::CommandCoreImpl as CommandCoreCore>::new(op, params_json)
                    .map_err(err)?,
            ),
        })
    }
    /// Plan the first command (or finish immediately). Returns the JSON-encoded
    /// `CommandStep` (`{ type: "run", request }` or `{ type: "done", result }`).
    #[napi(js_name = "start")]
    pub fn start(&self) -> Result<String> {
        self.core.start().map_err(err)
    }
    /// Consume the JSON-encoded `CommandOutput` (`{ code, stdout, stderr }`) of
    /// the last planned command and plan the next one (or finish). Returns the
    /// JSON-encoded `CommandStep`.
    #[napi(js_name = "advance")]
    pub fn advance(&self, output_json: String) -> Result<String> {
        self.core.advance(output_json).map_err(err)
    }
}

/// The Rust-backed faux core, exposed to JavaScript as `FauxCore`.
///
/// The JS `registerFauxProvider` shim constructs one of these, keeps the response
/// queue in JS, and calls [`FauxCore::stream_resolved`] (or
/// [`FauxCore::empty_queue_result`]) per stream. Cross-call state (call count and
/// prompt cache) lives in the wrapped [`FauxProvider`].
#[napi]
pub struct FauxCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::FauxCoreImpl>,
}

#[napi]
impl FauxCore {
    /// Build a faux core from pi's `RegisterFauxProviderOptions`, JSON-encoded.
    #[napi(constructor)]
    pub fn new(options_json: String) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::FauxCoreImpl as FauxCoreCore>::new(options_json).map_err(err)?,
            ),
        })
    }
    /// Set the `now` (epoch milliseconds) the provider reads when stamping the
    /// empty-queue/aborted message timestamps. The JS shim calls this with
    /// `Date.now()` before each stream so those timestamps track JS time.
    #[napi(js_name = "setNowMs")]
    pub fn set_now_ms(&self, now_ms: i64) -> () {
        self.core.set_now_ms(now_ms)
    }
    /// The provider's api id (pi's `core.api`).
    #[napi(js_name = "api")]
    pub fn api(&self) -> String {
        self.core.api()
    }
    /// The model catalog as a JSON array (pi's `core.models`).
    #[napi(js_name = "modelsJson")]
    pub fn models_json(&self) -> Result<String> {
        self.core.models_json().map_err(err)
    }
    /// pi's `getModel()`: the model with `id`, or the first model when `id` is
    /// omitted. Returns `null` when no model matches.
    #[napi(js_name = "getModelJson")]
    pub fn get_model_json(&self, id: Option<String>) -> Result<Option<String>> {
        self.core.get_model_json(id).map_err(err)
    }
    /// Increment and return the call count (pi's `state.callCount++`). The JS
    /// shim calls this before resolving a response factory, matching pi's order.
    #[napi(js_name = "bumpCallCount")]
    pub fn bump_call_count(&self) -> i64 {
        self.core.bump_call_count()
    }
    /// The current call count without incrementing (pi's `state.callCount`).
    #[napi(js_name = "callCount")]
    pub fn call_count(&self) -> i64 {
        self.core.call_count()
    }
    /// Stream an already-resolved response message, returning the
    /// `{ events, message }` result as JSON. The JS shim passes the message it
    /// popped (or computed from a factory); Rust applies pi's clone + usage
    /// estimate + delta streaming. `aborted` reproduces the pre-aborted signal
    /// path (pi's `signal.aborted`).
    #[napi(js_name = "streamResolved")]
    pub fn stream_resolved(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
        message_json: String,
        aborted: bool,
    ) -> Result<String> {
        self.core
            .stream_resolved(
                model_json,
                context_json,
                options_json,
                message_json,
                aborted,
            )
            .map_err(err)
    }
    /// The result pi streams when the response queue is empty (an `error`-stop
    /// message with usage estimated), as JSON.
    #[napi(js_name = "emptyQueueResult")]
    pub fn empty_queue_result(
        &self,
        model_json: String,
        context_json: String,
        options_json: Option<String>,
    ) -> Result<String> {
        self.core
            .empty_queue_result(model_json, context_json, options_json)
            .map_err(err)
    }
}

/// The Rust-backed stdin splitter, exposed to JavaScript as `StdinBufferCore`.
///
/// The JS `StdinBuffer` shim owns one of these, keeps pi's `EventEmitter` surface
/// and completion timer in TS, and per chunk: converts any `Buffer` to a string,
/// calls [`StdinBufferCore::process`], and replays the returned events onto the
/// emitter. All cross-chunk state (buffer, paste mode, pending Kitty codepoint)
/// lives entirely in the wrapped [`StdinBuffer`].
#[napi]
pub struct StdinBufferCore {
    // pub(crate): the @manual ops in lib.rs extend this class and need the core
    pub(crate) core: Arc<crate::core_impl::StdinBufferCoreImpl>,
}

#[napi]
impl StdinBufferCore {
    /// Build a buffer. `timeout_ms` mirrors pi's `StdinBufferOptions.timeout`
    /// (default 10); it is retained for parity — the completion timer itself is
    /// driven by the JS shim, so this value does not affect native splitting.
    #[napi(constructor)]
    pub fn new(timeout_ms: Option<i64>) -> Result<Self> {
        Ok(Self {
            core: Arc::new(
                <crate::core_impl::StdinBufferCoreImpl as StdinBufferCoreCore>::new(timeout_ms)
                    .map_err(err)?,
            ),
        })
    }
    /// pi's `StdinBuffer.process`. Accumulate `data`, and return every event the
    /// buffer produced for this chunk (complete `data` sequences and any
    /// `paste`), in emission order. The incomplete remainder is retained and can
    /// be read with [`StdinBufferCore::get_buffer`].
    #[napi(js_name = "process")]
    pub fn process(&self, data: String) -> Vec<StdinEventJs> {
        self.core.process(data)
    }
    /// pi's `StdinBuffer.flush`: emit the buffered incomplete remainder verbatim
    /// as a list of `data` payload strings (empty when nothing is buffered), and
    /// reset the remainder.
    #[napi(js_name = "flush")]
    pub fn flush(&self) -> Vec<String> {
        self.core.flush()
    }
    /// pi's `StdinBuffer.getBuffer`: the currently buffered incomplete remainder.
    #[napi(js_name = "getBuffer")]
    pub fn get_buffer(&self) -> String {
        self.core.get_buffer()
    }
    /// pi's `StdinBuffer.clear` / `destroy`: drop all buffered state.
    #[napi(js_name = "clear")]
    pub fn clear(&self) -> () {
        self.core.clear()
    }
}
