//! Unit tests for the faux provider, proving byte-compatibility with pi.
//!
//! The primary proof is the `events.json` fixture, generated by
//! `conformance/gen-ai-fixtures.ts` from pi's own `createFauxCore().stream`
//! (`vendor/pi/packages/ai/src/providers/faux.ts`) with a fixed token size. This
//! test builds the Rust faux provider with the identical inputs and asserts the
//! serialized event sequence matches the fixture exactly.

// straitjacket-allow-file[:duplication] — each `#[test]` builds the same provider
// / model / context fixture and asserts on the resulting stream; the parallel
// arrange-act bodies and the `json_eq` numeric-deep-equality helper (mirroring
// `tests/roundtrip.rs`) read as duplicates but are distinct, load-bearing cases.

use super::*;
use crate::seams::clock::FakeClock;
use crate::types::{UserContent, UserMessage, UserRole};
use serde_json::json;

const FIXED_TIMESTAMP: i64 = 1_700_000_000_004;

fn user_message(text: &str, timestamp: i64) -> Message {
    Message::User(UserMessage {
        role: UserRole::User,
        content: UserContent::Text(text.to_string()),
        timestamp,
    })
}

/// Reproduce `conformance/gen-ai-fixtures.ts` `collectEvents()`: a faux core with
/// `tokenSize { min: 4096, max: 4096 }`, one queued response of thinking + tool
/// call + text, streamed for a single "go" user message.
fn golden_provider() -> FauxProvider {
    FauxProvider::with_clock(
        RegisterFauxProviderOptions {
            api: Some("faux".to_string()),
            provider: Some("faux".to_string()),
            token_size_min: Some(4096),
            token_size_max: Some(4096),
            ..RegisterFauxProviderOptions::default()
        },
        std::sync::Arc::new(FakeClock::new(FIXED_TIMESTAMP)),
    )
}

fn golden_response() -> AssistantMessage {
    faux_assistant_message(
        vec![
            faux_thinking("reasoning"),
            faux_tool_call(
                "lookup",
                json!({ "id": 7 }),
                Some("tool-fixed-4".to_string()),
            ),
            faux_text("answer"),
        ],
        FauxAssistantOptions {
            stop_reason: Some(StopReason::ToolUse),
            timestamp: Some(FIXED_TIMESTAMP),
            ..FauxAssistantOptions::default()
        },
        FIXED_TIMESTAMP,
    )
}

fn fixture(name: &str) -> serde_json::Value {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path:?}: {e}"));
    serde_json::from_str(&raw).unwrap()
}

#[test]
fn faux_stream_matches_pi_events_fixture() {
    let provider = golden_provider();
    provider.set_responses([golden_response().into()]);

    let model = provider.get_model(None).expect("default model");
    let context = Context {
        messages: vec![user_message("go", 1_700_000_000_000)],
        ..Context::default()
    };
    let result = provider.stream(&model, &context, None, None);

    let produced = serde_json::to_value(&result.events).unwrap();
    let expected = fixture("events.json");
    assert!(
        json_eq(&produced, &expected),
        "faux event stream diverged from pi's events.json fixture\n produced: {produced:#}\n expected: {expected:#}"
    );
}

/// Numeric-aware deep JSON equality: a whole number pi writes as `0` and the
/// port re-emits as `0.0` from an `f64` cost field are the same JS number at the
/// napi boundary (see `tests/roundtrip.rs`). Structure and strings compare exactly.
fn json_eq(a: &serde_json::Value, b: &serde_json::Value) -> bool {
    use serde_json::Value;
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => match (x.as_f64(), y.as_f64()) {
            (Some(fx), Some(fy)) => fx == fy,
            _ => x == y,
        },
        (Value::Array(xs), Value::Array(ys)) => {
            xs.len() == ys.len() && xs.iter().zip(ys).all(|(x, y)| json_eq(x, y))
        }
        (Value::Object(xs), Value::Object(ys)) => {
            xs.len() == ys.len()
                && xs
                    .iter()
                    .all(|(k, x)| ys.get(k).is_some_and(|y| json_eq(x, y)))
        }
        _ => a == b,
    }
}

#[test]
fn faux_stream_event_kinds_and_final_usage() {
    let provider = golden_provider();
    provider.set_responses([golden_response().into()]);
    let model = provider.get_model(None).unwrap();
    let context = Context {
        messages: vec![user_message("go", 1_700_000_000_000)],
        ..Context::default()
    };
    let result = provider.stream(&model, &context, None, None);

    let kinds: Vec<&str> = result.events.iter().map(event_kind).collect();
    assert_eq!(
        kinds,
        [
            "start",
            "thinking_start",
            "thinking_delta",
            "thinking_end",
            "toolcall_start",
            "toolcall_delta",
            "toolcall_end",
            "text_start",
            "text_delta",
            "text_end",
            "done",
        ]
    );

    // Usage estimate: prompt "user:go" -> ceil(7/4)=2 input; assistant text
    // "reasoning\nlookup:{\"id\":7}\nanswer" (32 chars) -> ceil(32/4)=8 output.
    assert_eq!(result.message.usage.input, 2);
    assert_eq!(result.message.usage.output, 8);
    assert_eq!(result.message.usage.total_tokens, 10);
    assert_eq!(result.message.stop_reason, StopReason::ToolUse);
    assert_eq!(provider.call_count(), 1);
}

fn event_kind(e: &AssistantMessageEvent) -> &'static str {
    match e {
        AssistantMessageEvent::Start { .. } => "start",
        AssistantMessageEvent::TextStart { .. } => "text_start",
        AssistantMessageEvent::TextDelta { .. } => "text_delta",
        AssistantMessageEvent::TextEnd { .. } => "text_end",
        AssistantMessageEvent::ThinkingStart { .. } => "thinking_start",
        AssistantMessageEvent::ThinkingDelta { .. } => "thinking_delta",
        AssistantMessageEvent::ThinkingEnd { .. } => "thinking_end",
        AssistantMessageEvent::ToolcallStart { .. } => "toolcall_start",
        AssistantMessageEvent::ToolcallDelta { .. } => "toolcall_delta",
        AssistantMessageEvent::ToolcallEnd { .. } => "toolcall_end",
        AssistantMessageEvent::Done { .. } => "done",
        AssistantMessageEvent::Error { .. } => "error",
    }
}

#[test]
fn empty_queue_yields_error_event() {
    let provider = golden_provider();
    let model = provider.get_model(None).unwrap();
    let context = Context {
        messages: vec![user_message("hi", 0)],
        ..Context::default()
    };
    let result = provider.stream(&model, &context, None, None);
    assert_eq!(result.events.len(), 1);
    assert!(matches!(
        result.events[0],
        AssistantMessageEvent::Error { .. }
    ));
    assert_eq!(result.message.stop_reason, StopReason::Error);
    assert_eq!(
        result.message.error_message.as_deref(),
        Some("No more faux responses queued")
    );
}

#[test]
fn pre_aborted_signal_yields_aborted_error() {
    let provider = golden_provider();
    provider.set_responses([golden_response().into()]);
    let model = provider.get_model(None).unwrap();
    let context = Context {
        messages: vec![user_message("go", 0)],
        ..Context::default()
    };
    let signal = AbortSignal::aborted();
    let result = provider.stream(&model, &context, None, Some(&signal));
    assert_eq!(result.events.len(), 1);
    match &result.events[0] {
        AssistantMessageEvent::Error { reason, error } => {
            assert_eq!(*reason, StopReason::Aborted);
            assert_eq!(error.error_message.as_deref(), Some("Request was aborted"));
            assert_eq!(error.timestamp, FIXED_TIMESTAMP);
        }
        other => panic!("expected aborted error, got {other:?}"),
    }
}

#[test]
fn session_cache_accounts_prefix_on_second_call() {
    // First call with a session id writes the whole prompt to cache; the second
    // call with a longer prompt sharing the prefix reads the cached prefix and
    // writes only the delta. Mirrors pi's withUsageEstimate (faux.ts:213-251).
    let provider = golden_provider();
    let model = provider.get_model(None).unwrap();
    let options = StreamOptions {
        session_id: Some("s1".to_string()),
        cache_retention: None,
    };

    // Call 1: prompt "user:go" (7 utf16 units) -> cacheWrite=ceil(7/4)=2, input=2.
    provider.set_responses([faux_assistant_message(
        vec![faux_text("ok")],
        FauxAssistantOptions {
            timestamp: Some(1),
            ..Default::default()
        },
        1,
    )
    .into()]);
    let ctx1 = Context {
        messages: vec![user_message("go", 0)],
        ..Context::default()
    };
    let r1 = provider.stream(&model, &ctx1, Some(&options), None);
    assert_eq!(r1.message.usage.cache_write, 2);
    assert_eq!(r1.message.usage.cache_read, 0);
    assert_eq!(r1.message.usage.input, 2);

    // Call 2: prompt "user:going" (10 units). Cached prefix "user:go" is 7 units
    // -> cacheRead=ceil(7/4)=2; remaining "ing" 3 units -> cacheWrite=ceil(3/4)=1;
    // input=promptTokens(ceil(10/4)=3)-cacheRead(2)=1.
    provider.set_responses([faux_assistant_message(
        vec![faux_text("ok")],
        FauxAssistantOptions {
            timestamp: Some(2),
            ..Default::default()
        },
        2,
    )
    .into()]);
    let ctx2 = Context {
        messages: vec![user_message("going", 0)],
        ..Context::default()
    };
    let r2 = provider.stream(&model, &ctx2, Some(&options), None);
    assert_eq!(r2.message.usage.cache_read, 2);
    assert_eq!(r2.message.usage.cache_write, 1);
    assert_eq!(r2.message.usage.input, 1);
}
