//! GENERATED by fluessig bindgen from atilla.tsp (api layer). Do not edit.
//! straitjacket-allow-file:duplication — generated by fluessig; edit the schema instead
#![allow(clippy::all)]
#![allow(unused_imports)]

// The fixed prelude — generated code uses fully-qualified paths elsewhere.
use ext_php_rs::prelude::*;
use std::sync::Arc;
use std::time::Duration;
// The shared streaming contract — Poll/PollStream live in the fluessig-runtime crate.
use fluessig_runtime::{Poll, PollStream};

/// A core-layer failure becomes a thrown PHP exception (PHP is synchronous,
/// so a fallible op returns `PhpResult` and ext-php-rs raises on `Err`).
fn err(e: impl std::fmt::Display) -> PhpException {
    PhpException::default(e.to_string())
}

/// The `Atilla` contract — implement over the engine in `crate::core_impl`.
pub trait AtillaCore: Sized + Send + Sync + 'static {
    fn version() -> anyhow::Result<String>;
}

#[php_class]
pub struct Atilla;

#[php_impl]
impl Atilla {
    /// The atilla engine version, as reported by the atilla-core facade.
    /// PHP: Atilla::version(): string
    pub fn version() -> PhpResult<String> {
        <crate::core_impl::AtillaImpl as AtillaCore>::version().map_err(err)
    }
}

/// Registers the extension's surface with PHP.
#[php_module]
pub fn module(module: ModuleBuilder) -> ModuleBuilder {
    module
}
