//! PHP native extension for pidgin, built with `ext-php-rs` as a `cdylib`.
//!
//! The `Pidgin` class — its `version()` method, the `PidginCore` trait, and the
//! single `#[php_module]` registrar — is GENERATED by fluessig from the façade
//! api schema (`schema/api.json`) into `src/generated.rs` (do-not-edit;
//! regenerate with `./regen.sh`). The engine wiring behind that generated trait
//! is hand-written in [`core_impl`].
//!
//! The `Pidgin\Session` class is hand-authored in [`session`] (fluessig does not
//! model stateful/streaming session objects yet).
//!
//! # Module mounting
//!
//! ext-php-rs 0.13.1 registers every `#[php_class]` through the one crate-wide
//! `#[php_module]` (in `generated.rs`), emitting each class's `RegisteredClass`
//! impl at that macro's call site by **bare** identifier — so `Session` must be
//! in scope there. We must not edit `generated.rs`, and neither `include!` nor a
//! plain `mod generated;` can inject a name while keeping correct macro-expansion
//! order. So `build.rs` derives `generated.wired.rs` (an exact copy of
//! `generated.rs` plus one `use crate::session::Session;`) and we mount it as a
//! `#[path]` file module. `generated.rs` itself stays untouched and regenerable.

mod core_impl;
mod session;

#[path = "generated.wired.rs"]
mod generated;
