//! PHP native extension for atilla, built with `ext-php-rs` as a `cdylib`.
//!
//! The PHP-visible surface — the `#[php_class] Atilla`, its methods, the
//! `AtillaCore` trait, and the `#[php_module]` registrar — is GENERATED by
//! fluessig from the façade api schema (`schema/api.json`) and lives in
//! [`generated`]. The engine wiring behind the generated trait is hand-written
//! in [`core_impl`]. Regenerate with `./regen.sh` (see README.md); never edit
//! `src/generated.rs` by hand.
//!
//! The single `#[php_module]` entry point comes from the generated module, so
//! this crate registers exactly one extension.

mod core_impl;
mod generated;
