//! GENERATED by fluessig bindgen from @earendil-works/pi-orchestrator (via hinzu api-fluessig) (rust-core). Do not edit.
//! A self-contained Rust API skeleton: DTO models/enums + `<Interface>Core`
//! traits. Depends only on `anyhow`.
#![allow(dead_code)]
#![allow(clippy::all)]

// straitjacket-allow-file:duplication -- generated bindgen output; the repeated
// DTO derive/field shapes are inherent to the emitter, not a hand-written clone.
// This file lives under notes/ and is never compiled by the workspace.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InstanceStatus {
    Starting,
    Online,
    Stopping,
    Stopped,
    Error,
}

#[derive(Debug, Clone)]
pub struct ErrorResponse {
    pub r#type: String,
    pub ok: bool,
    pub error: String,
}

#[derive(Debug, Clone)]
pub struct InstanceRecord {
    pub id: String,
    pub status: InstanceStatus,
    pub cwd: String,
    pub createdAt: String,
    pub lastSeenAt: Option<String>,
    pub label: Option<String>,
    pub sessionId: Option<String>,
    pub sessionFile: Option<String>,
    pub radiusPiId: Option<String>,
}

#[derive(Debug, Clone)]
pub struct InstanceSummary {
    pub id: String,
    pub status: InstanceStatus,
    pub cwd: String,
    pub label: Option<String>,
    pub sessionId: Option<String>,
    pub sessionFile: Option<String>,
    pub radiusPiId: Option<String>,
}

#[derive(Debug, Clone)]
pub struct IpcRequestHandler {}

#[derive(Debug, Clone)]
pub struct ListRequest {
    pub r#type: String,
}

#[derive(Debug, Clone)]
pub struct ListResponse {
    pub r#type: String,
    pub instances: Option<Vec<InstanceSummary>>,
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone)]
pub struct MachineRecord {
    pub id: String,
    pub createdAt: String,
    pub lastSeenAt: Option<String>,
    pub label: Option<String>,
}

#[derive(Debug, Clone)]
pub struct RadiusRegistration {
    pub heartbeatIntervalMs: f64,
    pub expiresInMs: f64,
}

#[derive(Debug, Clone)]
pub struct RequestMap {
    pub spawn: SpawnRequest,
    pub list: ListRequest,
    pub stop: StopRequest,
    pub status: StatusRequest,
    pub rpc: RpcRequest,
    pub rpc_stream: RpcStreamRequest,
}

#[derive(Debug, Clone)]
pub struct ResponseBase {
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone)]
pub struct ResponseMap {
    pub spawn: SpawnResponse,
    pub list: ListResponse,
    pub stop: StopResponse,
    pub status: StatusResponse,
    pub rpc: RpcBridgeResponse,
    pub rpc_stream: RpcReadyResponse,
}

#[derive(Debug, Clone)]
pub struct RpcBridgeResponse {
    pub r#type: String,
    pub response: String,
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone)]
pub struct RpcReadyResponse {
    pub r#type: String,
    pub instance: Option<InstanceSummary>,
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone)]
pub struct RpcRequest {
    pub r#type: String,
    pub instanceId: String,
    pub command: String,
}

#[derive(Debug, Clone)]
pub struct RpcStreamRequest {
    pub r#type: String,
    pub instanceId: String,
}

#[derive(Debug, Clone)]
pub struct SpawnRequest {
    pub r#type: String,
    pub cwd: String,
    pub label: Option<String>,
    pub provider: Option<String>,
    pub model: Option<String>,
}

#[derive(Debug, Clone)]
pub struct SpawnResponse {
    pub r#type: String,
    pub instance: Option<InstanceSummary>,
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone)]
pub struct StatusRequest {
    pub r#type: String,
    pub instanceId: String,
}

#[derive(Debug, Clone)]
pub struct StatusResponse {
    pub r#type: String,
    pub instance: Option<InstanceSummary>,
    pub ok: bool,
    pub error: Option<String>,
}

#[derive(Debug, Clone)]
pub struct StopRequest {
    pub r#type: String,
    pub instanceId: String,
}

#[derive(Debug, Clone)]
pub struct StopResponse {
    pub r#type: String,
    pub instanceId: Option<String>,
    pub ok: bool,
    pub error: Option<String>,
}

/// The `OrchestratorSupervisor` contract — implement over the engine in `crate::core_impl`.
pub trait OrchestratorSupervisorCore: Sized + Send + Sync + 'static {
    fn get_instance(instance_id: String) -> anyhow::Result<Option<InstanceRecord>>;
    fn get_live_instance(instance_id: String) -> anyhow::Result<Option<InstanceRecord>>;
    fn handle_rpc(instance_id: String, command: String) -> anyhow::Result<Option<String>>;
    fn list_instances() -> anyhow::Result<Vec<InstanceRecord>>;
    fn list_live_instances() -> anyhow::Result<Vec<InstanceRecord>>;
    fn open_rpc_stream(
        instance_id: String,
        on_event: String,
        on_ui_request: String,
    ) -> anyhow::Result<Option<String>>;
    fn recover_after_restart() -> anyhow::Result<()>;
    fn shutdown() -> anyhow::Result<()>;
    fn spawn_instance(options: String) -> anyhow::Result<InstanceRecord>;
    fn stop_instance(instance_id: String) -> anyhow::Result<Option<InstanceRecord>>;
    fn update_instance(instance: InstanceRecord) -> anyhow::Result<()>;
}

/// The `PiOrchestrator` contract — implement over the engine in `crate::core_impl`.
pub trait PiOrchestratorCore: Sized + Send + Sync + 'static {
    fn create_rpc_process_instance(options: String) -> anyhow::Result<String>;
    fn delete_machine() -> anyhow::Result<()>;
    fn encode_message(message: String) -> anyhow::Result<String>;
    fn get_auth_path() -> anyhow::Result<String>;
    fn get_instance(instance_id: String) -> anyhow::Result<Option<InstanceRecord>>;
    fn get_instances_path() -> anyhow::Result<String>;
    fn get_machine_path() -> anyhow::Result<String>;
    fn get_orchestrator_dir() -> anyhow::Result<String>;
    fn get_socket_path() -> anyhow::Result<String>;
    fn handle_ipc_request(request: SpawnRequest) -> anyhow::Result<String>;
    fn load_instances() -> anyhow::Result<Vec<InstanceRecord>>;
    fn load_machine() -> anyhow::Result<Option<MachineRecord>>;
    fn open_rpc_stream(
        instance_id: String,
        on_response: String,
        on_session_event: String,
        on_ui_request: String,
    ) -> anyhow::Result<Option<String>>;
    fn parse_request_line(line: String) -> anyhow::Result<String>;
    fn parse_response_line(line: String) -> anyhow::Result<String>;
    fn remove_instance(instance_id: String) -> anyhow::Result<()>;
    fn save_instances(instances: Vec<InstanceRecord>) -> anyhow::Result<()>;
    fn save_machine(machine: MachineRecord) -> anyhow::Result<()>;
    fn send_ipc_request(request: String) -> anyhow::Result<String>;
    fn serve() -> anyhow::Result<()>;
    fn start_ipc_server(handler: IpcRequestHandler) -> anyhow::Result<String>;
    fn upsert_instance(instance: InstanceRecord) -> anyhow::Result<()>;
}

/// The `RpcProcessInstance` contract — implement over the engine in `crate::core_impl`.
pub trait RpcProcessInstanceCore: Sized + Send + Sync + 'static {
    fn dispose() -> anyhow::Result<()>;
    fn handle_ui_response(response: String) -> anyhow::Result<()>;
    fn on_event(listener: String) -> anyhow::Result<String>;
    fn on_exit(listener: String) -> anyhow::Result<String>;
    fn send(command: String) -> anyhow::Result<String>;
    fn set_ui_request_handler(handler: Option<String>) -> anyhow::Result<()>;
}
